---
title: "Reading 100 abstracts on \"Citizen science\""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

These are the top 100 abstracts from google scholar using the search term "Citizen science", since 2019.


### 1) Strasser, Bruno, et al. "" Citizen Science"? Rethinking Science and Public Participation." Science & Technology Studies 32.ARTICLE (2019): 52-76.

Since the late twentieth century, “citizen science” has become an increasingly fashionable label for a growing number of participatory research activities. This paper situates the origins and rise of the term “citizen science” and offers a new framework to better understand the diversity of epistemic practices involved in these participatory projects. It contextualizes “citizen science” within the broader history of public participation in science and analyzes critically the current promises—democratization, education, discoveries—emerging within the “citizen science” discourse. Finally, it maps a number of historical, political, and social questions for future research in the critical studies of “citizen science.”

### 2) Heigl, Florian, et al. "Opinion: Toward an international definition of citizen science." Proceedings of the National Academy of Sciences 116.17 (2019): 8089-8092. 

*This is a comment, not an article*

Public participation in scientific projects is flourishing globally as part of projects labeled “citizen science” (CS). Already, a number of professional networks for CS stakeholders have been founded, for example, the US-based Citizen Science Association, the European Citizen Science Association, and the Australian Citizen Science Association.

But what exactly qualifies as CS? It is interpreted in various ways (1) and takes different forms with different degrees of participation (2). In fact, the label CS is currently assigned to research activities either by project principal investigators (PIs) themselves or by research funding agencies. Against this backdrop, critical observers of CS, such as Guerrini et al. (3), have drawn attention to important legal and ethical issues including intellectual property and scientific integrity. Similarly, Vayena and Tasioulas (4) note the importance of protecting the interests of research participants in biomedical participant-led research, and Buyx et al. (5) note the need for a solidarity-based practice of CS to fully exploit its potential, making “every participant a PI.”

In light of the rapid growth of CS, present concerns, and calls for further improving the value of CS, we see several issues for policymakers, funding agencies, and citizens. Specifically, we believe that researchers and participants should move toward a shared understanding of what CS is, what it is not, and what criteria CS projects must fulfill to ensure high-quality participatory research (6). Establishing criteria will help ensure that CS projects are rigorous, help the field flourish, and where applicable encourage policymakers to take CS project data and results seriously.

### 3) Phillips, Tina B., et al. "Engagement in science through citizen science: Moving beyond data collection." Science Education 103.3 (2019): 665-690.

To date, most studies of citizen science engagement focus on quantifiable measures related to the contribution of data or other output measures. Few studies have attempted to qualitatively characterize citizen science engagement across multiple projects and from the perspective of the participants. Building on pertinent literature and sociocultural learning theories, this study operationalizes engagement in citizen science through an analysis of interviews of 72 participants from six different environmentally based projects. We document engagement in citizen science through an examination of cognitive, affective, social, behavioral, and motivational dimensions. We assert that engagement in citizen science is enhanced by acknowledging these multiple dimensions and creating opportunities for volunteers to find personal relevance in their work with scientists. A Dimensions of Engagement framework is presented that can facilitate the innovation of new questions and methodologies for studying engagement in citizen science and other forms of informal science education.

### 4) Callaghan, Corey T., et al. "Improving big citizen science data: moving beyond haphazard sampling." PLoS biology 17.6 (2019): e3000357.

Citizen science is mainstream: millions of people contribute data to a growing array of citizen science projects annually, forming massive datasets that will drive research for years to come. Many citizen science projects implement a “leaderboard” framework, ranking the contributions based on number of records or species, encouraging further participation. But is every data point equally “valuable?” Citizen scientists collect data with distinct spatial and temporal biases, leading to unfortunate gaps and redundancies, which create statistical and informational problems for downstream analyses. Up to this point, the haphazard structure of the data has been seen as an unfortunate but unchangeable aspect of citizen science data. However, we argue here that this issue can actually be addressed: we provide a very simple, tractable framework that could be adapted by broadscale citizen science projects to allow citizen scientists to optimize the marginal value of their efforts, increasing the overall collective knowledge.

### 5) Fritz, Steffen, et al. "Citizen science and the United Nations sustainable development goals." Nature Sustainability 2.10 (2019): 922-930.

Traditional data sources are not sufficient for measuring the United Nations Sustainable Development Goals. New and non-traditional sources of data are required. Citizen science is an emerging example of a non-traditional data source that is already making a contribution. In this Perspective, we present a roadmap that outlines how citizen science can be integrated into the formal Sustainable Development Goals reporting mechanisms. Success will require leadership from the United Nations, innovation from National Statistical Offices and focus from the citizen-science community to identify the indicators for which citizen science can make a real contribution.

### 6) Wiggins, Andrea, and John Wilbanks. "The rise of citizen science in health and biomedical research." The American Journal of Bioethics 19.8 (2019): 3-14.

Citizen science models of public participation in scientific research represent a growing area of opportunity for health and biomedical research, as well as new impetus for more collaborative forms of engagement in large-scale research. However, this also surfaces a variety of ethical issues that both fall outside of and build upon the standard human subjects concerns in bioethics. This article provides background on citizen science, examples of current projects in the field, and discussion of established and emerging ethical issues for citizen science in health and biomedical research.

### 7) van Etten, Jacob, et al. "Crop variety management for climate adaptation supported by citizen science." Proceedings of the National Academy of Sciences 116.10 (2019): 4194-4199.

Climate adaptation requires farmers to adjust their crop varieties over time and use the right varieties to minimize climate risk. Generating variety recommendations for farmers working in marginal, heterogeneous environments requires variety evaluation under farm conditions. On-farm evaluation is difficult to scale with conventional methods. We used a scalable approach to on-farm participatory variety evaluation using crowdsourced citizen science, assigning small experimental tasks to many volunteering farmers. We generated a unique dataset from 12,409 trial plots in Nicaragua, Ethiopia, and India, a participatory variety evaluation dataset of large size and scope. We show the potential of crowdsourced citizen science to generate insights into variety adaptation, recommend adapted varieties, and help smallholder farmers respond to climate change.

### 8) Elliott, Kevin C., and Jon Rosenberg. "Philosophical foundations for citizen science." Citizen Science: Theory and Practice 4.1 (2019).

*I read this last year, have notes (in the office I can't acces 'sigh' )*

Citizen science is increasingly being recognized as an important approach for gathering data, addressing community needs, and creating fruitful engagement between citizens and professional scientists. Nevertheless, the implementation of citizen science projects can be hampered by a variety of barriers. Some of these are practical (e.g., lack of funding or lack of training for both professional scientists and volunteers), but others are theoretical barriers having to do with concerns about whether citizen science lives up to standards of good scientific practice. These concerns about the overall quality of citizen science are ethically significant, because it is ethically problematic to waste resources on low-quality research, and it is also problematic to denigrate or dismiss research that is of high quality. Scholarship from the philosophy of science is well-placed to address these theoretical barriers, insofar as it is fundamentally concerned about the nature of good scientific inquiry. This paper examines three important concerns: (1) the worry that citizen science is not appropriately hypothesis-driven; (2) the worry that citizen science does not generate sufficiently high-quality data or use sufficiently rigorous methods; and (3) the worry that citizen science is tainted by advocacy and is therefore not sufficiently disinterested. We show that even though some of these concerns may be relevant to specific instances of citizen science, none of these three concerns provides a compelling reason to challenge the overall quality of citizen science in principle.

### 9) Altwegg, Res, and James D. Nichols. "Occupancy models for citizen‐science data." Methods in Ecology and Evolution 10.1 (2019): 8-21.

1. Large‐scale citizen‐science projects, such as atlases of species distribution, are an important source of data for macroecological research, for understanding the effects of climate change and other drivers on biodiversity, and for more applied conservation tasks, such as early‐warning systems for biodiversity loss.
2. However, citizen‐science data are challenging to analyse because the observation process has to be taken into account. Typically, the observation process leads to heterogeneous and non‐random sampling, false absences, false detections, and spatial correlations in the data. Increasingly, occupancy models are being used to analyse atlas data.
3. We advocate a dual approach to strengthen inference from citizen science data for the questions the programme is intended to address: (a) the survey design should be chosen with a particular set of questions and associated analysis strategy in mind and (b) the statistical methods should be tailored not only to those questions but also to the specific characteristics of the data.
4. We review the consequences of particular survey design choices that typically need to be made in atlas‐style citizen‐science projects. These include spatial resolution of the sampling units, allocation of effort in space, and collection of information about the observation process. On the analysis side, we review extensions of the basic occupancy models that are frequently necessary with atlas data, including methods for dealing with heterogeneity, non‐independent detections, false detections, and violation of the closure assumption.
5. New technologies, such as cell‐phone apps and fixed remote detection devices, are revolutionizing citizen‐science projects. There is an opportunity to maximize the usefulness of the resulting datasets if the protocols are rooted in robust statistical designs and data analysis issues are being considered. Our review provides guidelines for designing new projects and an overview of the current methods that can be used to analyse data from such projects.

### 10) Willi, Marco, et al. "Identifying animal species in camera trap images using deep learning and citizen science." Methods in Ecology and Evolution 10.1 (2019): 80-91.


1. Ecologists often study wildlife populations by deploying camera traps. Large datasets are generated using this approach which can be difficult for research teams to manually evaluate. Researchers increasingly enlist volunteers from the general public as citizen scientists to help classify images. The growing number of camera trap studies, however, makes it ever more challenging to find enough volunteers to process all projects in a timely manner. Advances in machine learning, especially deep learning, allow for accurate automatic image classification. By training models using existing datasets of images classified by citizen scientists and subsequent application of such models on new studies, human effort may be reduced substantially. The goals of this study were to (a) assess the accuracy of deep learning in classifying camera trap data, (b) investigate how to process datasets with only a few classified images that are generally difficult to model, and (c) apply a trained model on a live online citizen science project.
2. Convolutional neural networks (CNN s) were used to differentiate among images of different animal species, images of humans or vehicles, and empty images (no animals, vehicles, or humans). We used four different camera trap datasets featuring a wide variety of species, different habitats, and a varying number of images. All datasets were labelled by citizen scientists on Zooniverse.
3. Accuracies for identifying empty images across projects ranged between 91.2% and 98.0%, whereas accuracies for identifying specific species were between 88.7% and 92.7%. Transferring information from CNN s trained on large datasets (“transfer‐learning”) was increasingly beneficial as the size of the training dataset decreased and raised accuracy by up to 10.3%. Removing low‐confidence predictions increased model accuracies to the level of citizen scientists. By combining a trained model with classifications from citizen scientists, human effort was reduced by 43% while maintaining overall accuracy for a live experiment running on Zooniverse.
4. Ecology researchers can significantly reduce image classification time and manual effort by combining citizen scientists and CNN s, enabling faster processing of data from large camera trap studies.

### 11) Poisson, Autumn C., et al. "Quantifying the contribution of citizen science to broad‐scale ecological databases." Frontiers in Ecology and the Environment 18.1 (2020): 19-26.

Ecological research increasingly relies on broad‐scale databases containing information collected by personnel from a variety of sources, including government agencies, universities, and citizen‐science programs. However, the contribution of citizen‐science programs to these databases is not well known. We analyzed one such database to quantify the contribution of citizen science to lake water‐quality data from seven US states. Citizen‐science programs not only provided over half of the observations for commonly sampled water‐quality measures (water clarity, nutrients, and algal biomass) from the past 31 years, but also contributed to the majority of long‐term monitoring (>15 years) for selected measures in lakes. While previous studies have demonstrated the usefulness of citizen science for research, management, policy, and public engagement, our study demonstrates that citizen science can also make valuable contributions to populating broad‐scale ecological databases. Strengthening partnerships between citizen‐science programs and monitoring agencies can help maintain and expand spatial and temporal data coverage during the “big data” era of ecology.

### 12) Auerbach, Jeremy, et al. "The problem with delineating narrow criteria for citizen science." Proceedings of the National Academy of Sciences 116.31 (2019): 15336-15337.

*This is a letter and a response to 2)"*

Heigl et al. (1) propose an international definition of citizen science based on quality criteria for projects. As an international group of scholars with extensive background in the theory and practice of citizen science, we find the Opinion by Heigl et al. (1) antithetical to the creativity, innovation, and bottom-up pathways to knowledge generation that are embodied by citizen science. The minimum quality standards Heigl et al. (1) propose do not represent the interdisciplinary consensus of the international citizen science community*, and we fear that such a definition would confine rather than define the field.

Many citizen science professionals, including some of the authors of this letter, have attempted to define citizen science in the past, only to discover later that their definition does not fully encompass the field (2). We also strongly believe that it is both unproductive and fraught to narrowly define citizen science based on a set of quality criteria for individual projects. In addition, we note that, practically speaking, a classification system for citizen science projects based on quality criteria is not equivalent to a definition.

Such an approach also excludes several types of citizen science. For example, Heigl et al. (1) restrict their concept of citizen science to include only projects in which groups of citizens gather data for a predefined scientific purpose, generally reflecting contributory-style projects that represent only one component of the larger citizen science landscape. As a result, many long-standing examples of citizen science are not included in their definition, such as amateur astronomers who independently make systematic observations of our universe (3).

Heigl et al. (1) propose criteria that they claim will “help the field flourish, and … encourage policymakers to take [citizen science] project data and results seriously.” While defining criteria for inclusion is entirely reasonable for many purposes (e.g., project funding), those criteria will depend strongly on the situation. For example, some existing agencies have already developed definitions that meet their needs (4), and as with other scientific data citizen science data, should of course be evaluated as to its fitness for purpose. It is important to recognize, however, that citizen science also extends well beyond development and testing of research hypotheses, including activities such as environmental monitoring, producing training data for supervised machine learning, data visualization and interpretation, and complex problem solving.

We argue that Heigl et al.’s (1) specified minimum quality criteria should not be used as “the basis for an international declaration” because any exclusionary approach will necessarily fail to address the “challenge of accommodating considerable heterogeneity” within the field of citizen science. Instead of focusing on specific criteria, we advocate for collaboration among all engaged actors to emphasize informed consent about project design features and transparency in data collection and handling practices (to indicate data quality and fitness for purpose). We encourage the citizen science community and associated collaborators (such as funding agencies) to determine the best design specifications for their own unique contexts, enabling citizen science to achieve its full potential.

### 13) Mahajan, Sachit, et al. "A citizen science approach for enhancing public understanding of air pollution." Sustainable Cities and Society 52 (2020): 101800.

The deterioration in air quality is a challenging problem worldwide. There is a need to raise awareness among the people and support informed decision making. Over the years, citizen science activities have been implemented for environmental monitoring and raising awareness but most of such works are contributory in nature, i.e. task design, planning and analysis are performed by professional researchers and citizens act as participants. Our objective is to demonstrate that citizen science can be used as a ‘tool’ to enhance public understanding of air pollution by engaging communities and local stakeholders. We present a co-creation based citizen science approach which incorporates the ideas of inclusion, where citizens are involved in most of the steps of the scientific process; collaboration, where the citizen scientists define research problems and methodologies, and reciprocation, where citizen scientists share their observations through storytelling. We integrate the use of interactive air quality quizzes, offline questionnaires and low-cost air quality monitoring sensors. The results show that such methods can generate insightful data which can assist in understanding people’s perception and exposure levels at a fine-grained level. It was also observed that community engagement in air quality monitoring can enhance partnerships between the community and research fraternity.

### 14) Sorte, Frank A. La, and Marius Somveille. "Survey completeness of a global citizen‐science database of bird occurrence." Ecography 43.1 (2020): 34-43.

Measuring the completeness of survey inventories created by citizen‐science initiatives can identify the strengths and shortfalls in our knowledge of where species occur geographically. Here, we use occurrence information from eBird to measure the survey completeness of the world's birds in this database at three temporal resolutions and four spatial resolutions across the annual cycle during the period 2002 to 2018. Approximately 84% of the earth's terrestrial surface contained bird occurrence information with the greatest concentrations occurring in North America, Europe, India, Australia and New Zealand. The largest regions with low levels of survey completeness were located in central South America, northern and central Africa, and northern Asia. Across spatial and temporal resolutions, survey completeness in regions with occurrence information was 55–74% on average, with the highest values occurring at coarser temporal and coarser spatial resolutions and during spring migration within temperate and boreal regions. Across spatial and temporal resolutions, survey completeness exceeded 90% within ca 4–14% of the earth's terrestrial surface. Survey completeness increased globally from 2002 to 2018 across all months of the year at a rate of ca 3% yr–1. The slowest gains occurred in Africa and in montane regions, and the most rapid gains occurred in India and in tropical forests after 2012. Thus, occurrence information from a global citizen‐science program for a charismatic and well‐studied taxon was geographically broad but contained heterogeneous patterns of survey completeness that were strongly influenced by temporal and especially spatial resolution. Our results identify regions where the application of additional effort would address current knowledge shortfalls, and regions where the maintenance of existing effort would benefit long‐term monitoring efforts. Our findings highlight the potential of citizen science initiatives to further our knowledge of where species occur across space and time, information whose applications under global change will likely increase.

### 15) Rambonnet, Liselotte, et al. "Making citizen science count: Best practices and challenges of citizen science projects on plastics in aquatic environments." Marine pollution bulletin 145 (2019): 271-277.

There is considerable scientific and societal concern about plastic pollution, which has resulted in citizen science projects to study the scale of the issue. Citizen science is a cost-effective way to gather data over a large geographical range while simultaneously raising public awareness on the problem. Because the experiences of researchers involved in these projects are not yet adequately covered, this paper presents the findings from ten semi-structured qualitative interviews with researchers leading a citizen science project on micro- or macroplastics. Our results show it is important to specify the goal(s) of the project and that expertise on communication and data science is needed. Furthermore, simple protocols, quality control, and engagement with volunteers and the public are key elements for successful projects. From these results, a framework with recommendations was drafted, which can be used by anyone who wants to develop or improve citizen science projects.

### 16) Kelling, Steve, et al. "Using semistructured surveys to improve citizen science data for monitoring biodiversity." BioScience 69.3 (2019): 170-179.

Biodiversity is being lost at an unprecedented rate, and monitoring is crucial for understanding the causal drivers and assessing solutions. Most biodiversity monitoring data are collected by volunteers through citizen science projects, and often crucial information is lacking to account for the inevitable biases that observers introduce during data collection. We contend that citizen science projects intended to support biodiversity monitoring must gather information about the observation process as well as species occurrence. We illustrate this using eBird, a global citizen science project that collects information on bird occurrences as well as vital contextual information on the observation process while maintaining broad participation. Our fundamental argument is that regardless of what species are being monitored, when citizen science projects collect a small set of basic information about how participants make their observations, the scientific value of the data collected will be dramatically improved.

### 17) Gilfedder, Mat, et al. "Brokering trust in citizen science." Society & natural resources 32.3 (2019): 292-302.

Citizen science (CS) information requires systematic review that incorporates a range of interests and concerns. Yet, there has been little research on what might constitute reviewing best practice to ensure CS is trusted by contributors and users of the data. Insights from a survey of all 1134 reviewers who curate the global eBird Project highlight the knowledge-brokering work involved to ensure CS data are trusted by both citizens and science. Drawing on scholarship focused on key drivers of useable knowledge for natural resource decision-making, we consider CS reviewing best practice to ensure CS can be useful to the producers and users of this knowledge. We find that CS reviewers need to be motivated to provide appropriate feedback to improve CS data, commit to reviewing practice that is respected by citizens, and ensure the information published is credible and be reviewed by a supportive and accountable network of fellow reviewers.

### 18) Lambers, Karsten, Wouter B. Verschoof-van der Vaart, and Quentin PJ Bourgeois. "Integrating remote sensing, machine learning, and citizen science in Dutch archaeological prospection." Remote Sensing 11.7 (2019): 794.

Although the history of automated archaeological object detection in remotely sensed data is short, progress and emerging trends are evident. Among them, the shift from rule-based approaches towards machine learning methods is, at the moment, the cause for high expectations, even though basic problems, such as the lack of suitable archaeological training data are only beginning to be addressed. In a case study in the central Netherlands, we are currently developing novel methods for multi-class archaeological object detection in LiDAR data based on convolutional neural networks (CNNs). This research is embedded in a long-term investigation of the prehistoric landscape of our study region. We here present an innovative integrated workflow that combines machine learning approaches to automated object detection in remotely sensed data with a two-tier citizen science project that allows us to generate and validate detections of hitherto unknown archaeological objects, thereby contributing to the creation of reliable, labeled archaeological training datasets. We motivate our methodological choices in the light of current trends in archaeological prospection, remote sensing, machine learning, and citizen science, and present the first results of the implementation of the workflow in our research area. 

### 19) Lukyanenko, Roman, Andrea Wiggins, and Holly K. Rosser. "Citizen science: An information quality research frontier." Information Systems Frontiers (2019): 1-23.

The rapid proliferation of online content producing and sharing technologies resulted in an explosion of user-generated content (UGC), which now extends to scientific data. Citizen science, in which ordinary people contribute information for scientific research, epitomizes UGC. Citizen science projects are typically open to everyone, engage diverse audiences, and challenge ordinary people to produce data of highest quality to be usable in science. This also makes citizen science a very exciting area to study both traditional and innovative approaches to information quality management. With this paper we position citizen science as a leading information quality research frontier. We also show how citizen science opens a unique opportunity for the information systems community to contribute to a broad range of disciplines in natural and social sciences and humanities.

### 20) Crowston, Kevin, Erica Mitchell, and Carsten Østerlund. "Coordinating advanced crowd work: extending citizen science." Citizen Science: Theory and Practice 4.1 (2019).

This paper presents a case study of an online citizen science project that attempted to involve volunteers in tasks with multiple dependencies including analyzing bulk data as well as interpreting data and writing a paper for publication. Tasks with more dependencies call for more elaborate coordination mechanisms. However, the relationship between the project and its volunteers limits how work can be coordinated. Contrariwise, a mismatch between dependencies and available coordination mechanisms can lead to performance problems, as were seen in the case. The results of the study suggest recommendations for design of online citizen science projects for advanced tasks.

### 21) Rowbotham, Samantha, et al. "Does citizen science have the capacity to transform population health science?." Critical Public Health 29.1 (2019): 118-128.

Citizen science engages members of the public in research design, data collection, and analysis – in asking and answering questions about the world around them. The United States, European Union, and Australia have placed citizen science at the forefront of national science policy. Journals such as Science, Nature and Bioscience regularly feature projects conducted by citizens. Citizen science engages millions of people worldwide. However, to date, population health science has not relied heavily on citizen contributions. Although community-based participatory action research remains a strong foundational method to engage those affected by public health problems, there is additional potential to mainstream population health through wider, less intensive opportunities to be involved in our science. If we are to tackle the complex challenges that face population health then new avenues are needed to capture the energy and attention of citizens who may not feel affected by public health problems, i.e. to engage the ‘by-standers’ in population health science. Particular types of citizen science methods have the potential to do this. But simply increasing the breadth and volume of scientific evidence will not be enough. Complex, intractable, macro-level problems in population health require change in how our journals and funding bodies respond to data generated by the public. Of course, democratisation of science and the potential decentralisation of scientific authority will bring deep challenges. But potentially it brings a future where population health science is better known, understood and respected, with benefits for the types of public policies that derive from this science.

### 22) Katapally, Tarun Reddy. "The SMART framework: integration of citizen science, community-based participatory research, and systems science for population health science in the digital age." JMIR mHealth and uHealth 7.8 (2019): e14056.

Citizen science enables citizens to actively contribute to all aspects of the research process, from conceptualization and data collection, to knowledge translation and evaluation. Citizen science is gradually emerging as a pertinent approach in population health research. Given that citizen science has intrinsic links with community-based research, where participatory action drives the research agenda, these two approaches could be integrated to address complex population health issues. Community-based participatory research has a strong record of application across multiple disciplines and sectors to address health inequities. Citizen science can use the structure of community-based participatory research to take local approaches of problem solving to a global scale, because citizen science emerged through individual environmental activism that is not limited by geography. This synergy has significant implications for population health research if combined with systems science, which can offer theoretical and methodological strength to citizen science and community-based participatory research. Systems science applies a holistic perspective to understand the complex mechanisms underlying causal relationships within and between systems, as it goes beyond linear relationships by utilizing big data–driven advanced computational models. However, to truly integrate citizen science, community-based participatory research, and systems science, it is time to realize the power of ubiquitous digital tools, such as smartphones, for connecting us all and providing big data. Smartphones have the potential to not only create equity by providing a voice to disenfranchised citizens but smartphone-based apps also have the reach and power to source big data to inform policies. An imminent challenge in legitimizing citizen science is minimizing bias, which can be achieved by standardizing methods and enhancing data quality—a rigorous process that requires researchers to collaborate with citizen scientists utilizing the principles of community-based participatory research action. This study advances SMART, an evidence-based framework that integrates citizen science, community-based participatory research, and systems science through ubiquitous tools by addressing core challenges such as citizen engagement, data management, and internet inequity to legitimize this integration.


### 23) Keshavan, Anisha, Jason D. Yeatman, and Ariel Rokem. "Combining citizen science and deep learning to amplify expertise in neuroimaging." Frontiers in neuroinformatics 13 (2019): 29.

Big Data promises to advance science through data-driven discovery. However, many standard lab protocols rely on manual examination, which is not feasible for large-scale datasets. Meanwhile, automated approaches lack the accuracy of expert examination. We propose to (1) start with expertly labeled data, (2) amplify labels through web applications that engage citizen scientists, and (3) train machine learning on amplified labels, to emulate the experts. Demonstrating this, we developed a system to quality control brain magnetic resonance images. Expert-labeled data were amplified by citizen scientists through a simple web interface. A deep learning algorithm was then trained to predict data quality, based on citizen scientist labels. Deep learning performed as well as specialized algorithms for quality control (AUC = 0.99). Combining citizen science and deep learning can generalize and scale expert decision making; this is particularly important in disciplines where specialized, automated tools do not yet exist.

### 24) Panofsky, Aaron, and Joan Donovan. "Genetic ancestry testing among white nationalists: From identity repair to citizen science." Social studies of science 49.5 (2019): 653-681.

White nationalists have a genetic essentialist understanding of racial identity, so what happens when using genetic ancestry tests (GATs) to explore personal identities, they receive upsetting results they consider evidence of non-white or non-European ancestry? Our answer draws on qualitative analysis of posts on the white nationalist website Stormfront, interpreted by synthesizing the literatures on white nationalism and GATs and identity. We show that Stormfront posters exert much more energy repairing individuals’ bad news than using it to exclude or attack them. Their repair strategies combine anti-scientific, counter-knowledge attacks on the legitimacy of GATs and quasi-scientific reinterpretations of GATs in terms of white nationalist histories. However, beyond individual identity repair they also reinterpret the racial boundaries and hierarchies of white nationalism in terms of the relationships GATs make visible. White nationalism is not simply an identity community or political movement but should be understood as bricoleurs with genetic knowledge displaying aspects of citizen science.

### 25) Trouille, Laura, Chris J. Lintott, and Lucy F. Fortson. "Citizen science frontiers: Efficiency, engagement, and serendipitous discovery with human–machine systems." Proceedings of the National Academy of Sciences 116.6 (2019): 1902-1909.

Citizen science has proved to be a unique and effective tool in helping science and society cope with the ever-growing data rates and volumes that characterize the modern research landscape. It also serves a critical role in engaging the public with research in a direct, authentic fashion and by doing so promotes a better understanding of the processes of science. To take full advantage of the onslaught of data being experienced across the disciplines, it is essential that citizen science platforms leverage the complementary strengths of humans and machines. This Perspectives piece explores the issues encountered in designing human–machine systems optimized for both efficiency and volunteer engagement, while striving to safeguard and encourage opportunities for serendipitous discovery. We discuss case studies from Zooniverse, a large online citizen science platform, and show that combining human and machine classifications can efficiently produce results superior to those of either one alone and how smart task allocation can lead to further efficiencies in the system. While these examples make clear the promise of human–machine integration within an online citizen science system, we then explore in detail how system design choices can inadvertently lower volunteer engagement, create exclusionary practices, and reduce opportunity for serendipitous discovery. Throughout we investigate the tensions that arise when designing a human–machine system serving the dual goals of carrying out research in the most efficient manner possible while empowering a broad community to authentically engage in this research.

### 26) Giovos, Ioannis, et al. "Citizen-science for monitoring marine invasions and stimulating public engagement: a case project from the eastern Mediterranean." Biological Invasions 21.12 (2019): 3707-3721.

The distribution of marine life has been alarmingly reshaped lately and the number of non-indigenous species and their impacts are rapidly escalating globally. Timely and accurate information about the occurrence of non-indigenous species are of major importance for the mitigation of the issue. However, still large gaps in knowledge about marine bioinvasion exist. Mediterranean Sea is among the most impacted ecoregions globally. In this work we present a comprehensive overview of the project “Is is Alien to you? Share it!!!” which monitors non-indigenous species in Greece and Cyprus with the help of citizen scientists. The goal of this work is to present this project as a case study in order to demonstrate how citizen science can substantially contribute to the monitoring of biological invasions. We compared the projects database with the databased of ELNAIS and EASIN, for discuss weaknesses and advantages and future steps for advancing the effort. In total 691 records of marine alien and cryptogenic species were collected in these 2 years from Greece and Cyprus, with the density of records reaching 20 observations per km2 in some locations. The project has contributed significantly in the assessment of descriptor D2 “Exotic Species” of the Marine Strategy Framework Directive, with 3 new species for Greece. Future steps should focus on training citizens to report less reported taxa and raising the awareness of all relevant stakeholders.

### 27) Turbé, Anne, et al. "Understanding the citizen science landscape for European environmental policy: an assessment and recommendations." Citizen Science: Theory and Practice 4.1 (2019).

Citizen science is increasingly upheld with the potential to underpin all aspects of the environmental policy process. However, to date, contributions of citizen science to environmental decision-making remain sparse and not well understood. Evidence points to a gap between the potential relevance of citizen science for policy and its actual implementation. We lack a comprehensive assessment of the current impacts of citizen science projects on environmental policy, and an identification of the scientific, engagement, and governance characteristics of projects that facilitate successful contributions to policy. This paper addresses that knowledge gap through identifying the characteristics of citizen science projects that support policy. We present an inventory of 503 citizen science projects with environmental policy relevance, and an in-depth analysis of 45 case examples with quantitative assessment of characteristics of the citizen scientist, scientific, socio-economic, and policy dimensions. Our results demonstrate that citizen science can underpin all steps of the environmental policy process, and that a diversity of approaches can be used to achieve this. However, governmental support, scientific excellence, and NGO-leadership facilitate policy linkages. We discuss the main challenges and opportunities identified by project leaders in linking citizen science and policy and present a set of recommendations for promoting the better integration of citizen science in the different phases of the policy cycle. Central among these are clarifying policy needs, facilitating access to citizen science data, and improving their evaluation and recognition by decision-makers.

### 28) Johnston, Alison, et al. "Estimating species distributions from spatially biased citizen science data." Ecological Modelling 422 (2020): 108927.

Ecological citizen science data are rapidly growing in availability and use in ecology and conservation. Many citizen science projects have the flexibility for participants to select where they survey, resulting in more participants, but also spatially biased data. It is important to assess the extent to which these spatially biased data can provide reliable estimates of species distributions. Here we quantify the extent of site selection bias in a citizen science project and the implications of this spatial bias in species distribution models. Using data from the BirdTrack citizen science project in Great Britain from 2007 to 2011, we modelled the spatial bias of data submissions. We next produced species occupancy models for 138 bird species, and assessed the impact of accounting for spatial bias. We compared the distributions to those produced using unbiased data from an Atlas survey from the same region and time period. Averaging across 138 species, models with spatially biased data produced accurate and precise estimates of species occupancy for most locations in Great Britain. However, these distributions were both less accurate and less precise in the Scottish Highlands, showing on average a positive bias. Accounting for the spatially biased sampling with weights led to on average greater accuracy in the Scottish Highlands, but did not increase precision. This region is both distinct in environmental characteristics and has a low density of observations, making it difficult to characterise environmental relationships with species occupancy. Accounting for the spatially biased sampling did not affect average accuracy or precision throughout most of the country. Spatially biased citizen science data can be used to estimate species occupancy in regions with stationary environmental relationships and good sampling across environmental space. The reliability of estimated species distributions from spatially biased data should be further validated and tested under a range of different scenarios.

### 29) King, Abby C., et al. "Maximizing the promise of citizen science to advance health and prevent disease." Preventive medicine 119 (2019): 44.

“Citizen science”—a field with an increasingly broad collection of definitions, terms, and standards worldwide (Eitzel et al., 2017; European Citizen Science Association, 2015; Standards Development Partnership, 2018; Woolley et al., 2016)—can be described generally as laypersons participating in the research process for purposes of scientific advancement (Kelty and Panofsky, 2014). The field has gained increasing interest in medical and broader health fields both in the U.S. and internationally (Den Broeder et al., 2018; Eitzel et al., 2017; Standards Development Partnership, 2018). In the current climate of confusion and mistrust of scientific inquiry among some, efforts to engage community members in the scientific process can demystify science and make it more accessible and inclusive (Kelty and Panofsky, 2014). At the same time, citizen science can aid in advancing biomedical and other health-related discoveries and impacts (Jasanoff, 2006; Kelty and Panofsky, 2014; Nowotny, 2014). As important, in light of the aging U.S. population, escalating health costs, and widespread health disparities, leveraging the power of the public as change agents in promoting health-enhancing conditions can complement the work of health professionals. This can potentially produce additional benefits for population health. However, maximizing the advantages that citizen science offers the health sciences requires expansion of thought and action beyond the more limited definitions currently being emphasized in the U.S. health arena (Rowbotham et al., 2017; Woolley et al., 2016).

### 30) Füchslin, Tobias, Mike S. Schäfer, and Julia Metag. "Who wants to be a citizen scientist? Identifying the potential of citizen science and target segments in Switzerland." Public Understanding of Science 28.6 (2019): 652-668.

Driven by the proliferation of digital media, citizen science – the involvement of non-scientists in scientific research – represents one of the most important recent developments in science communication as it brings science and the public closer together. So far, however, citizen science projects have mostly attracted people that are highly educated, mostly male and already have very positive attitudes towards science. Based on nationally representative survey data (N = 1051), our study explores the potential of citizen science in Switzerland. Using regression analysis, we show that attitudes towards science are significant antecedents of respondents’ interest in participating in citizen science – but that gender and education are not. In addition, latent class analysis identifies five segments, representing over one-third of the Swiss population, who are interested in citizen science and could potentially be engaged: ‘Free-Timers’, ‘Senior Sciencephiles’, ‘Young Sciencephiles’, ‘Intrigued Adolescents’ and ‘Fully Employed Parents’. Additional description suggests that previously overlooked segments are best addressed online via YouTube or offline in zoos or botanical gardens. Overall, our analysis suggests that citizen science’s potential is far higher than previous projects were able to realize.

### 31) Pocock, Michael JO, et al. "Developing the global potential of citizen science: Assessing opportunities that benefit people, society and the environment in East Africa." Journal of applied ecology 56.2 (2019): 274-281.

1. Citizen science is gaining increasing prominence as a tool for science and engagement. However, despite being a potentially valuable tool for sustainable development, citizen science has little visibility in many developing countries.
2. We undertook a collaborative prioritisation process with experts in conservation and the environment to assess the potential of environmental citizen science in East Africa, including its opportunities, benefits and barriers. This provided principles that are applicable across developing countries, particularly for large‐scale citizen science.
3. We found that there was great potential for citizen science to add to our scientific knowledge of natural resources and biodiversity trends. Many of the important benefits of citizen science were for people, as well as the environment directly. Major barriers to citizen science were mostly social and institutional, although projects should also consider access to suitable technology and language barriers.
4. Policy implications . Citizen science can provide data to support decision‐making and reporting against international targets. Participation can also provide societal benefits, informing and empowering people, thus supporting the United Nations’ Sustainable Development Goals. In developing countries, innovation is needed to further develop culturally relevant citizen science that benefits participants and end users. This should be supported through regional networks of stakeholders for sharing best practice.

### 32) Njue, N., et al. "Citizen science in hydrological monitoring and ecosystem services management: State of the art and future prospects." Science of the Total Environment 693 (2019): 133531.

Hydrological monitoring is essential to guide evidence-based decision making necessary for sustainable water resource management and governance. Limited hydrometric datasets and the pressure on long-term hydrological monitoring networks make it paramount to explore alternative methods for data collection. This is particularly the case for low-income countries, where data scarcity is more pronounced, and where conventional monitoring methods are expensive and logistically challenging. Citizen science in hydrological research has recently gained popularity and crowdsourced monitoring is a promising cost-effective approach for data collection. Citizen science also has the potential to enhance knowledge co-creation and science-based evidence that underpins the governance and management of water resources. This paper provides a comprehensive review on citizen science and crowdsourced data collection within the context of hydrology, based on a synthesis of 71 articles from 2001 to 2018. Application of citizen science in hydrology is increasing in number and breadth, generating a plethora of scientific data. Citizen science approaches differ in scale, scope and degree of citizen involvement. Most of the programs are found in North America and Europe. Participation mostly comprises a contributory citizen science model, which engages citizens in data collection. In order to leverage the full potential of citizen science in knowledge co-generation, future citizen science projects in hydrology could benefit from more co-created types of projects that establish strong ties between research and public engagement, thereby enhancing the long-term sustainability of monitoring networks.

### 33) Ceccaroni, Luigi, et al. "Opportunities and risks for citizen science in the age of artificial intelligence." Citizen Science: Theory and Practice 4.1 (2019).

Members of the public are making substantial contributions to science as citizen scientists, and advances in technologies have enabled citizens to make even more substantial contributions. Technologies that allow computers and machines to function in an intelligent manner, often referred to as artificial intelligence (AI), are now being applied in citizen science. Discussions about guidelines, responsibilities, and ethics of AI usage are already happening outside the field of citizen science. We suggest such considerations should also be explored carefully in the context of citizen science applications. To start the conversation, we offer the citizen science community an essay to introduce the state-of-play for AI in citizen science and its potential uses in the future. We begin by presenting a systematic overview of AI technologies currently being applied, highlighting exemplary projects for each technology type described. We then discuss how AI is likely to be increasingly utilised in citizen science into the future, and, through scenarios, we explore both future opportunities and potential risks. Lastly, we conclude by providing recommendations that warrant consideration by the citizen science community, such as developing a data stewardship plan to inform citizens in advance of plans and expected outcomes of using data for AI training, or adopting good practice around anonymity. Our intent is for this essay to lead to further critical discussions among citizen science practitioners, which is needed for responsible, ethical, and useful use of AI in citizen science.

### 34) Sumner, Seirian, et al. "Mapping species distributions in 2 weeks using citizen science." Insect Conservation and Diversity 12.5 (2019): 382-388.

1. Ecological citizen science initiatives are growing in popularity with the increasing realisation of the potential for occurrence records to contribute information on biodiversity. Citizen science data are, however, justifiably criticised for misidentification, uneven sampling, incomplete detection or selective reporting.

2. Here, we test the accuracy of citizen science data for UK social wasp (Vespinae) species’ distributions. We compared data collected over 2 weeks by members of the public setting out baited traps across the UK and sending captured specimens for expert identification [1294 locations; 6680 wasps; three dominant species Vespula vulgaris (44%), Vespula germanica (44%) and Vespa crabro (6%)], with a four‐decade long‐term data set established by the Bees, Wasps and Ants Recording Society (BWARS ).

3. The citizen science data were significantly less spatially biased than the long‐term data, but they were more urban‐biased. Species distribution modelling showed that, for Vespa crabro , just 2 weeks of citizen science generated coverage comparable to more than four decades of expert recording.

4. Overall, we show that citizen science can be an extremely powerful and robust method for mapping insect diversity and distributions. We suggest that cautious combination of citizen science data with long‐term expert surveying could be a highly reliable method for monitoring biodiversity.

### 35) Johnston, A., et al. "Best practices for making reliable inferences from citizen science data: case study using eBird to estimate species distributions." BioRxiv (2019): 574392.

Citizen science data are valuable for addressing a wide range of ecological research questions, and there has been a rapid increase in the scope and volume of data available. However, data from large-scale citizen science projects typically present a number of challenges that can inhibit robust ecological inferences. These challenges include: species bias, spatial bias, variation in effort, and variation in observer skill.

To demonstrate key challenges in analysing citizen science data, we use the example of estimating species distributions with data from eBird, a large semi-structured citizen science project. We estimate three widely applied metrics for describing species distributions: encounter rate, occupancy probability, and relative abundance. For each method, we outline approaches for data processing and modelling that are suitable for using citizen science data for estimating species distributions.

Model performance improved when data processing and analytical methods addressed the challenges arising from citizen science data. The largest gains in model performance were achieved with two key processes 1) the use of complete checklists rather than presence-only data, and 2) the use of covariates describing variation in effort and detectability for each checklist. Including these covariates accounted for heterogeneity in detectability and reporting, and resulted in substantial differences in predicted distributions. The data processing and analytical steps we outlined led to improved model performance across a range of sample sizes.

When using citizen science data it is imperative to carefully consider the appropriate data processing and analytical procedures required to address the bias and variation. Here, we describe the consequences and utility of applying our suggested approach to semi-structured citizen science data to estimate species distributions. The methods we have outlined are also likely to improve other forms of inference and will enable researchers to conduct robust analyses and harness the vast ecological knowledge that exists within citizen science data.

### 36) Hecker, Susanne, et al. "How Does Policy Conceptualise Citizen Science? A Qualitative Content Analysis of International Policy Documents." Citizen Science: Theory and Practice 4.1 (2019).

Policy and science show great interest in citizen science as a means to public participation in research. To recognize how citizen science is perceived to foster joint working at the science-society-policy interface, a mutual understanding of the term “citizen science” is required. Here, we assess the conceptualisation and strategic use of the term “citizen science” in policy through a qualitative content analysis of 43 international policy documents edited by governments and authorities. Our results show that most documents embrace the diversity of the research approach and emphasize the many benefits that citizen science may provide for science, society, and policy. These include boosting spatio-temporal data collection through volunteers, tapping into distributed knowledge domains, increasing public interest and engagement in research, and enhancing societal relevance of the respective research. In addition, policy documents attribute educational benefits to citizen science by fostering scientific literacy, individual learning, and skill development, as well as by facilitating environmental stewardship. Through active participation, enhanced ownership of research results may improve policy decision-making processes and possibly democratise research as well as public policy processes, although the latter is mentioned only in a few European Union (EU) documents. Challenges of citizen science mentioned in the analysed policy documents relate mainly to data quality and management, to organisational and governance issues, and to difficulties of the uptake of citizen science results into actual policy implementation due to a lack of citizen science alignment with current policy structures and agendas. Interestingly, documents largely fail to address the benefits and challenges of citizen science as a tool for policy development, i.e., citizen science is mainly perceived as only a science tool. Overall, policy documents seem to be influenced strongly by the citizen science discourse in the science sector, which indicates a joint advocacy for citizen science.

### 37) Sun, Catherine C., J. Andrew Royle, and Angela K. Fuller. "Incorporating citizen science data in spatially explicit integrated population models." Ecology 100.9 (2019): e02777.

Information about population abundance, distribution, and demographic rates is critical for understanding a species’ ecology and for effective conservation and management. To collect data over large spatial and temporal extents for such inferences, especially for species with low densities or wide distributions, citizen science can be an efficient approach. Integrated models have also emerged as an important methodology to estimate population parameters by combining multiple types of data, including citizen science data. We developed a spatially explicit integrated model that combines opportunistically collected presence–absence (PA) data, commonly collected in citizen science efforts, with systematically collected spatial capture–recapture (SCR) data, which are often limited to small spatial and temporal extents. We conducted single and multi‐season simulations with parameters informed by North American black bear (Ursus americanus ) populations, to evaluate the influence of varying amounts of opportunistic PA data collected at larger spatial and temporal extents on the estimation of population‐level parameters. Integrating opportunistic PA data increased the precision and accuracy of posterior estimates of abundance, and survival and recruitment rates. In some cases, adding PA locations improved abundance estimates more than increasing PA detection probability. Posterior estimates were as precise and unbiased as when higher quality, but sparse, SCR data were available. We also applied the integrated model to SCR and citizen science PA data collected on black bears in New York, with results consistent with our simulations. Our findings indicate that citizen science in integrated models can be a cost‐efficient way to improve estimates of population parameters and increase the spatiotemporal extent of inference. Continued developments with integrated models and citizen science data will offer additional ways to improve our understanding of population structure and demographics.

### 38) Vohland, Katrin, Maike Weißpflug, and Lisa Pettibone. "Citizen Science and the Neoliberal Transformation of Science–an Ambivalent Relationship." Citizen Science: Theory and Practice 4.1 (2019).

The neoliberal turn in science has led to the economisation of knowledge, economic criteria for evaluating research, and a retreat of the state from governance of the scientific system. These steps have important ramifications for citizen science. On one hand, citizen science may add to the neoliberalization of science by filling gaps in “traditional science,” such as providing free environmental data or delivering public goods such as education or environmental knowledge. On the other hand, citizen science may provide a way to buck the trend of neoliberalization, by promoting new forms of societal cooperation and mutual learning that may lead to more social cohesion and sustainability, as well as safeguard a non-economized sphere. In this way, citizen science is ambivalent: It can either strengthen or challenge neoliberalization of science. This article describes this idea in more detail and presents practical suggestions for how to manage them, ranging from openly curated data over different types of feedback systems to the development of mutual learning spaces.

### 39) Quinlivan, Lauren, Deborah V. Chapman, and Timothy Sullivan. "Validating citizen science monitoring of ambient water quality for the United Nations sustainable development goals." Science of the Total Environment 699 (2020): 134255.

Citizen science (CS) may be described as research carried out by members of the public with the aim of gathering scientific information for the purpose of aiding in scientific projects. It has many potential advantages, including data collection at a scale not possible by professional scientists alone. The United Nations (UN) has recently recognized citizen science as a potential source of data that may contribute to the UN Sustainable Development Goals (SDGs). The availability of relatively inexpensive water quality monitoring field equipment suitable for CS suggests great potential for increased spatial coverage far beyond that of traditional, laboratory-based monitoring networks for water quality. In support of work towards the achievement of Sustainable Development Goal 6: “Clean Water and Sanitation”, this study tested the use of such field equipment by citizen scientists for SDG Indicator 6.3.2: “Proportion of bodies of water with good ambient water quality”. Data generated by 26 citizen scientists were compared with the results produced by an accredited laboratory. The results compared well for most parameters, suggesting that citizen science may be able to contribute towards monitoring ambient water quality for the Sustainable Development Goals.

### 40) Young, Bruce E., et al. "Using citizen science data to support conservation in environmental regulatory contexts." Biological Conservation 237 (2019): 57-62.

Outside of protected areas, environmental regulation is a vital policy tool for conserving at-risk species. An underappreciated potential for citizen science is to augment locality databases used in regulatory review to provide greater certainty to regulatory decisions. To characterize current use of citizen science data in regulatory review, we surveyed 61 state and provincial natural heritage programs, agencies that perform field surveys and maintain databases of at-risk species in the United States and Canada. Most (82% of U.S. and 88% of Canadian) natural heritage programs participate in regulatory review, and of these 52% of the U.S. and all Canadian programs currently use citizen science data. eBird and iNaturalist are the most commonly used schemes. In a test case with the New York Natural Heritage Program's database, the inclusion of eBird records for 6 at-risk species increased the currency and the number and spatial extent of areas known to be utilized by these species. Although citizen science data did not change subnational conservation status categories, they demonstratively complemented information collected by professional field biologists. Challenges to using citizen science data in this context include extracting useful information on rare species when most records are of common species and filtering records with sufficient spatial precision and documentation. To enhance the utility of their data, designers of citizen science schemes should encourage their volunteers to provide useful ancillary data, such as breeding activity for birds, and making data, including for sensitive species, easy to access by program data managers.

### 41) Kelly, Rachel, et al. "Social license through citizen science." Ecology and Society 24.1 (2019).

Active and meaningful public engagement is necessary to foster informed and publicly accepted natural resource management. Citizen science presents an important avenue by which to achieve such engagement. Citizen science is the active involvement of the public in science to address scientific questions, often of common interest or concern, by collecting and analyzing data, and publishing and communicating science via diverse outlets. Here, we explore whether and how citizen science can also play a role in generating social license for marine conservation, using European marine citizen science as a case study. Social license is a concept that reflects community views and expectations on the use and management of natural resources. To date, social license in the marine space has largely focused on public perceptions of industrial and extractive uses of the marine environment, and limited research has explored social license for conservation. We highlight important linkages between social license and citizen science that can work synergistically to support conservation. We use in-depth qualitative interviews and a semiquantitative online survey of marine citizen science coordinators to investigate how citizen science can play a role in enhancing social license and the mechanisms through which it can occur. Our findings indicate that citizen science can enhance social license by improving ocean literacy and marine citizenship. We demonstrate that marine citizen science has considerable potential to generate and develop social license for marine conservation in Europe and elsewhere.

### 42) Heilmann-Clausen, Jacob, et al. "How citizen science boosted primary knowledge on fungal biodiversity in Denmark." Biological Conservation 237 (2019): 366-372.

The Danish Fungal Atlas was a citizen science project aiming to map Danish macrofungi over five years (2009–13). The atlas contributed >235,000 records of fruit-body forming Basidiomycota, adding to about 195,000 fungal records from earlier periods. The new records increased the average number of species known per 10 km × 10 km grid cell by 75% from 125 to 218 species. We recorded 197 species as new to Denmark, extending the number of known basidiomycote species by 7%. At least 15 species appeared to be new to science. Among the new Danish records, species with northern distribution ranges were significantly overrepresented, in marked contrast to climate change predictions. Species with inconspicuous or subterranean fruit bodies were overrepresented among both the new Danish species and those only recorded before the project period, indicating low recording probability to be an important driver for the turnover in species recorded. Hence, the main drivers of novel fungal discoveries were 1) intensive sampling effort by citizen scientists guided by professional mycologists and 2) improved taxonomic knowledge. Summarizing over the last 100 years, an exponential increase in known macrofungal diversity in Denmark is evident, suggesting that we are still far from having a complete overview. This is striking, considering that Denmark is among the best-studied land areas on the globe. We conclude that citizen science projects, if appropriately designed, have a huge potential to boost primary knowledge on fungal biodiversity.

### 43) Sauermann, Henry, et al. "Citizen science and sustainability transitions." Research Policy 49.5 (2020): 103978.

Citizen Science (CS) projects involve members of the general public as active participants in research. While some advocates hope that CS can increase scientific knowledge production (“productivity view”), others emphasize that it may bridge a perceived gap between science and the broader society (“democratization view”). We discuss how an integration of both views can allow Citizen Science to support complex sustainability transitions in areas such as renewable energy, public health, or environmental conservation. We first identify three pathways through which such impacts can occur: (1) Problem identification and agenda setting; (2) Resource mobilization; and (3) Facilitating socio-technical co-evolution. To realize this potential, however, CS needs to address important challenges that emerge especially in the context of sustainability transitions: Increasing the diversity, level, and intensity of participation; addressing the social as well as technical nature of sustainability problems; and reducing tensions between CS and the traditional institution of academic science. Grounded in a review of academic literature and policy reports as well as a broad range of case examples, this article contributes to scholarship on science, innovation, and sustainability transitions. We also offer insights for actors involved in initiating or institutionalizing Citizen Science efforts, including project organizers, funding agencies, and policy makers.

### 44) Juang, Caroline S., Thomas A. Stanley, and Dalia B. Kirschbaum. "Using citizen science to expand the global map of landslides: Introducing the Cooperative Open Online Landslide Repository (COOLR)." PloS one 14.7 (2019): e0218657.

Robust inventories are vital for improving assessment of and response to deadly and costly landslide hazards. However, collecting landslide events in inventories is difficult at the global scale due to inconsistencies in or the absence of landslide reporting. Citizen science is a valuable opportunity for addressing some of these challenges. The new Cooperative Open Online Landslide Repository (COOLR) supplements data in a NASA-developed Global Landslide Catalog (GLC) with citizen science reports to build a more robust, publicly available global inventory. This manuscript introduces the COOLR project and its methods, evaluates the initial citizen science results from the first 13 months, and discusses future improvements to increase the global engagement with the project. The COOLR project (https://landslides.nasa.gov) contains Landslide Reporter, the first global citizen science project for landslides, and Landslide Viewer, a portal to visualize data from COOLR and other satellite and model products. From March 2018 to April 2019, 49 citizen scientists contributed 162 new landslide events to COOLR. These events spanned 37 countries in five continents. The initial results demonstrated that both expert and novice participants are contributing via Landslide Reporter. Citizen scientists are filling in data gaps through news sources in 11 different languages, in-person observations, and new landslide events occurring hundreds and thousands of kilometers away from any existing GLC data. The data is of sufficient accuracy to use in NASA susceptibility and hazard models. COOLR continues to expand as an open platform of landslide inventories with new data from citizen scientists, NASA scientists, and other landslide groups. Future work on the COOLR project will seek to increase participation and functionality of the platform as well as move towards collective post-disaster mapping.

### 45) Li, Enjie, et al. "An urban biodiversity assessment framework that combines an urban habitat classification scheme and citizen science data." Frontiers in Ecology and Evolution 7 (2019): 277.

A lack of information about urban habitats, and a lack of professionally-collected species occurrence data are often cited as major impediments to completing bioassessments in urban landscapes. We developed an urban biodiversity assessment framework that addresses these challenges. The proposed framework combines a customized hierarchical urban habitat classification scheme with citizen science-generated species occurrence data, such as iNaturalist and eBird. It integrates publicly available data on the physical and anthropogenic environment with species occurrence information and serves as a novel method for conducting urban biodiversity assessments. This framework provides insights into how species occurrences within an urban landscape are associated with spatial variation in the physical and anthropogenic environment. It can also yield information useful for planning and conservation management aimed at maintaining and enhancing the abundance and diversity of native and other desirable species in urban areas. This framework requires minimal taxonomic expertise on the part of those who employ it, and it can be implemented in urban areas worldwide, wherever adequate data exist. We demonstrate the application of this framework in the highly urbanized portion of Los Angeles County, California, USA. Our demonstration used 18 physical and anthropogenic variables to classify our study area into nine urban habitat types. We then assessed relationships between these urban habitat types with species occurrences using research-grade data from iNaturalist. This analysis detected significant differences in distributions of some species between these nine urban habitat types and demonstrated that the proposed framework can be used to conduct urban biodiversity assessments. With increasing availability of remote sensing data and publicly-generated biodiversity data, this framework may be used for analysis of urban areas around the globe.

### 46) Brown, Eleanor D., and Byron K. Williams. "The potential for citizen science to produce reliable and useful information in ecology." Conservation Biology 33.3 (2019): 561-569.

We examined features of citizen science that influence data quality, inferential power, and usefulness in ecology. As background context for our examination, we considered topics such as ecological sampling (probability based, purposive, opportunistic), linkage between sampling technique and statistical inference (design based, model based), and scientific paradigms (confirmatory, exploratory). We distinguished several types of citizen science investigations, from intensive research with rigorous protocols targeting clearly articulated questions to mass‐participation internet‐based projects with opportunistic data collection lacking sampling design, and examined overarching objectives, design, analysis, volunteer training, and performance. We identified key features that influence data quality: project objectives, design and analysis, and volunteer training and performance. Projects with good designs, trained volunteers, and professional oversight can meet statistical criteria to produce high‐quality data with strong inferential power and therefore are well suited for ecological research objectives. Projects with opportunistic data collection, little or no sampling design, and minimal volunteer training are better suited for general objectives related to public education or data exploration because reliable statistical estimation can be difficult or impossible. In some cases, statistically robust analytical methods, external data, or both may increase the inferential power of certain opportunistically collected data. Ecological management, especially by government agencies, frequently requires data suitable for reliable inference. With standardized protocols, state‐of‐the‐art analytical methods, and well‐supervised programs, citizen science can make valuable contributions to conservation by increasing the scope of species monitoring efforts. Data quality can be improved by adhering to basic principles of data collection and analysis, designing studies to provide the data quality required, and including suitable statistical expertise, thereby strengthening the science aspect of citizen science and enhancing acceptance by the scientific community and decision makers.

### 47) Honorato-Zimmer, Daniela, et al. "Inter-hemispherical shoreline surveys of anthropogenic marine debris–A binational citizen science project with schoolchildren." Marine pollution bulletin 138 (2019): 464-473.

Anthropogenic marine debris (AMD) is a global problem and the identification of its sources is essential for adequate mitigation strategies. Herein we examined whether AMD density and composition differed between two countries with contrasting socio-economic backgrounds and marine litter sources (i.e. Chile and Germany). In nationwide beach litter surveys, we used a citizen science approach with schoolchildren and their teachers. Litter densities were substantially higher in Chile than in Germany. The different geographic zones surveyed in both countries showed strong grouping tendencies according to their main economic activities (tourism, shipping, fisheries/aquaculture), major litter sources, and AMD composition, in terms of dominance and diversity of AMD types. The results suggest that beach litter composition can be used as a simple proxy to identify AMD sources, and also that law enforcement and education can help mitigate the problem; however, for efficient solutions, production and consumption of plastics must be reduced.

### 48) Eritja, Roger, et al. "First detection of Aedes japonicus in Spain: an unexpected finding triggered by citizen science." Parasites & vectors 12.1 (2019): 1-9.

Background:

Aedes japonicus is an invasive vector mosquito from Southeast Asia which has been spreading across central Europe since the year 2000. Unlike the Asian Tiger mosquito (Aedes albopictus) present in Spain since 2004, there has been no record of Ae. japonicus in the country until now.

Results:

Here, we report the first detection of Ae. japonicus in Spain, at its southernmost location in Europe. This finding was triggered by the citizen science platform Mosquito Alert. In June 2018, a citizen sent a report via the Mosquito Alert app from the municipality of Siero in the Asturias region (NW Spain) containing pictures of a female mosquito compatible with Ae. japonicus. Further information was requested from the participant, who subsequently provided several larvae and adults that could be classified as Ae. japonicus. In July, a field mission confirmed its presence at the original site and in several locations up to 9 km away, suggesting a long-time establishment. The strong media impact in Asturias derived from the discovery raised local participation in the Mosquito Alert project, resulting in further evidence from surrounding areas.

Conclusions:

Whilst in the laboratory Ae. japonicus is a competent vector for several mosquito-borne pathogens, to date only West Nile virus is a concern based on field evidence. Nonetheless, this virus has yet not been detected in Asturias so the vectorial risk is currently considered low. The opportunity and effectiveness of combining citizen-sourced data to traditional surveillance methods are discussed.

### 49) Shanley, Lea A., et al. "Policy Perspectives on Citizen Science and Crowdsourcing." Citizen Science: Theory and Practice 4.1 (2019).

The articles in this issue frame challenges and opportunities for citizen science, crowdsourcing, and policy development, and provide relevant case studies in local, regional, national, and international contexts. Topics span from local invasive species management to global sustainable development, and provide both frameworks and recommendations for further consideration.

### 50) Falk-Andersson, Jannike, Boris Woody Berkhout, and Tenaw Gedefaw Abate. "Citizen science for better management: Lessons learned from three Norwegian beach litter data sets." Marine pollution bulletin 138 (2019): 364-375.

Increased plastic consumption and poor waste management have resulted in litter representing an ever-increasing threat to the marine environment. To identify sources and evaluate mitigation measures, beach litter has been monitored. Using data from two citizen science protocols (CSPs) and OSPAR monitoring of Norwegian beaches, this study 1) identifies the most abundant litter types, 2) compares OSPAR to citizen science data, and 3) examines how to improve the management relevance of beach litter data. The dominant litter types were; food and drink- and fishery related items, and unidentifiable plastic pieces. Data from CSPs are consistent with OSPAR data in abundance and diversity, although few OSPAR beaches limit verification of CSP data. In contrast to OSPAR, the CSPs estimate the weight of the litter. CSPs lack important variables which could explain why some litter types are abundant in some particular areas. The latter could be improved by recording GPS positions.

### 51) Terry, J. Christopher D., Helen E. Roy, and Tom A. August. "Thinking like a naturalist: Enhancing computer vision of citizen science images by harnessing contextual data." Methods in Ecology and Evolution 11.2 (2020): 303-315.

1. The accurate identification of species in images submitted by citizen scientists is currently a bottleneck for many data uses. Machine learning tools offer the potential to provide rapid, objective and scalable species identification for the benefit of many aspects of ecological science. Currently, most approaches only make use of image pixel data for classification. However, an experienced naturalist would also use a wide variety of contextual information such as the location and date of recording.
2. Here, we examine the automated identification of ladybird (Coccinellidae) records from the British Isles submitted to the UK Ladybird Survey, a volunteer‐led mass participation recording scheme. Each image is associated with metadata; a date, location and recorder ID, which can be cross‐referenced with other data sources to determine local weather at the time of recording, habitat types and the experience of the observer. We built multi‐input neural network models that synthesize metadata and images to identify records to species level.
3. We show that machine learning models can effectively harness contextual information to improve the interpretation of images. Against an image‐only baseline of 48.2%, we observe a 9.1 percentage‐point improvement in top‐1 accuracy with a multi‐input model compared to only a 3.6% increase when using an ensemble of image and metadata models. This suggests that contextual data are being used to interpret an image, beyond just providing a prior expectation. We show that our neural network models appear to be utilizing similar pieces of evidence as human naturalists to make identifications.
4. Metadata is a key tool for human naturalists. We show it can also be harnessed by computer vision systems. Contextualization offers considerable extra information, particularly for challenging species, even within small and relatively homogeneous areas such as the British Isles. Although complex relationships between disparate sources of information can be profitably interpreted by simple neural network architectures, there is likely considerable room for further progress. Contextualizing images has the potential to lead to a step change in the accuracy of automated identification tools, with considerable benefits for large‐scale verification of submitted records.

### 52) Gouraguine, Adam, et al. "Citizen science in data and resource-limited areas: A tool to detect long-term ecosystem changes." PloS one 14.1 (2019): e0210007.

Coral reefs are threatened by numerous global and local stressors. In the face of predicted large-scale coral degradation over the coming decades, the importance of long-term monitoring of stress-induced ecosystem changes has been widely recognised. In areas where sustained funding is unavailable, citizen science monitoring has the potential to be a powerful alternative to conventional monitoring programmes. In this study we used data collected by volunteers in Southeast Sulawesi (Indonesia), to demonstrate the potential of marine citizen science programmes to provide scientifically sound information necessary for detecting ecosystem changes in areas where no alternative data are available. Data were collected annually between 2002 and 2012 and consisted of percent benthic biotic and abiotic cover and fish counts. Analyses revealed long-term coral reef ecosystem change. We observed a continuous decline of hard coral, which in turn had a significant effect on the associated fishes, at community, family and species levels. We provide evidence of the importance of marine citizen science programmes in detecting long-term ecosystem change as an effective way of delivering conservation data to local government and national agencies. This is particularly true for areas where funding for monitoring is unavailable, resulting in an absence of ecological data. For citizen science data to contribute to ecological monitoring and local decision-making, the data collection protocols need to adhere to sound scientific standards, and protocols for data evaluation need to be available to local stakeholders. Here, we describe the monitoring design, data treatment and statistical analyses to be used as potential guidelines in future marine citizen science projects.

### 53) Van Brussel, Suzanne, and Huib Huyse. "Citizen science on speed? Realising the triple objective of scientific rigour, policy influence and deep citizen engagement in a large-scale citizen science project on ambient air quality in Antwerp." Journal of Environmental Planning and Management 62.3 (2019): 534-551.

Citizen science projects are increasingly recognised as catalyst for triggering behaviour change and building social capital around environmental issues. However, overview studies observe recurrent challenges in many citizen science projects in terms of combining high levels of data quality with deep citizen engagement and policy influence. This paper reports on the findings of the CurieuzeNeuzen project (www.CurieuzeNeuzen.eu), a large-scale citizen science project on air quality in Antwerp, delivering results in the three areas described above. Through CurieuzeNeuzen, 2,000 citizens studied the air quality levels in and around Antwerp in 2016 and were intensively deliberating on possible causes and solutions. Surveys were conducted at the start and towards the end of the project, with participants stating that their participation resulted in changed views and behaviour towards air pollution, mobility solutions, and city planning. The findings were picked-up academically and contributed to policy debates on air quality at city and regional level.

### 54) Rasmussen, Lisa M., and Caren Cooper. "Citizen science ethics." Citizen Science: Theory and Practice 4.1 (2019).

*This is editorial content*

We are very pleased to present this special issue of Citizen Science: Theory and Practice dedicated to ethical issues in citizen science. Readers may wonder why an entire issue devoted to ethics in citizen science is warranted. After all, ethical issues in social media research have garnered more national media attention than issues in citizen science; the overwhelming majority of citizen science volunteers are not crying out for discussion about ethics; and federal regulators have not targeted the field for new or intensified scrutiny regarding ethical issues. Moreover, citizen scientists, practitioners, and participants seem well-intentioned and motivated to do good work in service of good aims. What’s the problem?...

### 55) Torney, Colin J., et al. "A comparison of deep learning and citizen science techniques for counting wildlife in aerial survey images." Methods in Ecology and Evolution 10.6 (2019): 779-787.

1. Fast and accurate estimates of wildlife abundance are an essential component of efforts to conserve ecosystems in the face of rapid environmental change. A widely used method for estimating species abundance involves flying aerial transects, taking photographs, counting animals within the images and then inferring total population size based on a statistical estimate of species density in the region. The intermediate task of manually counting the aerial images is highly labour intensive and is often the limiting step in making a population estimate.
2. Here, we assess the use of two novel approaches to perform this task by deploying both citizen scientists and deep learning to count aerial images of the 2015 survey of wildebeest (Connochaetes taurinus ) in Serengeti National Park, Tanzania.
3. Through the use of the online platform Zooniverse, we collected multiple non‐expert counts by citizen scientists and used three different aggregation methods to obtain a single count for the survey images. We also counted the images by developing a bespoke deep learning method via the use of a convolutional neural network. The results of both approaches were then compared.
4. After filtering of the citizen science counts, both approaches provided highly accurate total estimates. The deep learning method was far faster and appears to be a more reliable and predictable approach; however, we note that citizen science volunteers played an important role when creating training data for the algorithm. Notably, our results show that accurate, species‐specific, automated counting of aerial wildlife images is now possible.

### 56) Ripoll, Anna, et al. "Testing the performance of sensors for ozone pollution monitoring in a citizen science approach." Science of the total environment 651 (2019): 1166-1179.

Tropospheric ozone (O3) is an environmental pollutant of growing concern, especially in suburban and rural areas where the density of air quality monitoring stations is not high. In this type of areas citizen science strategies can be useful tools for awareness raising, but sensor technologies must be validated before sensor data are communicated to the public. In this work, the performance under field conditions of two custom-made types of ozone sensing devices, based on metal-oxide and electrochemical sensors, was tested. A large array of 132 metal-oxide (Sensortech MICS 2614) and 11 electrochemical (Alphasense) ozone sensors, built into 44 sensing devices, was co-located at reference stations in Italy (4 stations) and Spain (5). Mean R2 between sensor and reference data was 0.88 (0.78–0.96) and 0.89 (0.73–0.96) for Captor (metal-oxide) and Raptor (electrochemical) nodes. The metal-oxide sensors showed an upper limit (approximately 170 ug/m3) implying that these sensors may be useful to communicate mean ozone concentrations but not peak episodes. The uncertainty of the nodes was 10% between 100 and 150 ug/m3 and 20% between 150 and 200 ug/m3, for Captors, and 10% for >100 ug/m3 for Raptors. Operating both types of nodes up to 5 months did not evidence any clear influence of drifts. The use of these sensors in citizen science can be a useful tool for awareness raising. However, significant data processing efforts are required to ensure high data quality, and thus machine learning strategies are advisable. Relative uncertainties should always be reported when communicating ozone concentration data from sensing nodes.

### 57) Schuttler, Stephanie G., et al. "Citizen science in schools: Students collect valuable mammal data for science, conservation, and community engagement." Bioscience 69.1 (2019): 69-79.

Citizen science has been touted as an effective means to collect large-scale data while engaging the public. We demonstrate that children as young as 9 years old can collect valuable mammal monitoring data using camera traps while connecting with nature and learning through their own scientific discoveries. Indian, Kenyan, Mexican, and American students used camera traps near their schools and detected 13–37 species, all of which were verified by professionals. These data describe rich mammal faunas near schools, sometimes surpassing nearby protected areas, and included five endangered species. Ninety-four percent of the camera traps were set in accordance with scientific protocols, and the teachers reported the experience as highly engaging for their students. Furthermore, the generated photos and results had community-wide impacts involving local politicians, community members, and the media. We show that children can run sensors to contribute valid scientific data important for conservation and research.

### 58) Boersch-Supan, Philipp H., Amanda E. Trask, and Stephen R. Baillie. "Robustness of simple avian population trend models for semi-structured citizen science data is species-dependent." Biological Conservation 240 (2019): 108286.

Accurate and robust population monitoring is essential to effective biodiversity conservation. Citizen scientists are collecting opportunistic biodiversity records on unprecedented temporal and spatial scales, vastly outnumbering the records achievable from structured surveys. Opportunistic records may exhibit spatio-temporal biases and/or large heterogeneity in observer effort and skill, but the quantity-quality trade-offs between surveys and less structured schemes remain poorly understood.

Recent work has advocated the use of simple trend models for opportunistic biodiversity records. We examine the robustness of population trends of common United Kingdom birds derived from two citizen-science schemes; BirdTrack, an opportunistic recording scheme, and the structured Breeding Bird Survey (BBS). We derived reporting rate trends from BirdTrack lists using simple statistical models which accounted for list-level effort covariates but not for preferential sampling, and compared them to abundance and occurrence trends derived from BBS survey data.

For 90 out of 141 species, interannual changes in reporting rates were positively correlated with trends from structured surveys. Correlations were higher for widespread species and those exhibiting marked population change. We found less agreement among trends for rarer species and those with small or uncertain population trajectories. The magnitude of long-term changes in reporting rates was generally smaller than the magnitude of occupancy or abundance changes, but this relationship exhibited wide scatter, complicating the interpretability of reporting rate trends. Our findings suggest that simple statistical models for estimating population trends from opportunistic complete lists are robust only for widespread and common species, even in a scheme with many observers and extensive coverage.

### 59) Larson, Eric R., et al. "From eDNA to citizen science: emerging tools for the early detection of invasive species." Frontiers in Ecology and the Environment 18.4 (2020): 194-202.

Biological invasions are a form of global change threatening biodiversity, ecosystem stability, and human health, and cost government agencies billions of dollars in remediation and eradication programs. Attempts to eradicate introduced species are most successful when detection of newly established populations occurs early in the invasion process. We review existing and emerging tools – specifically environmental DNA (eDNA ), chemical approaches, remote sensing, citizen science, and agency‐based monitoring – for surveillance and monitoring of invasive species. For each tool, we consider the benefits provided, examine challenges and limitations, discuss data sharing and integration, and suggest best practice implementations for the early detection of invasive species. Programs that promote public participation in large‐scale biodiversity identification and monitoring (such as iN aturalist and eB ird) may be the best resources for early detection. However, data from these platforms must be monitored and used by agencies that can mount appropriate response efforts. Control efforts are more likely to succeed when they are focused on early detection and prevention, thereby saving considerable time and resources.

### 60) Davids, Jeffrey C., et al. "Citizen science flow—An assessment of simple streamflow measurement methods." Hydrol. Earth Syst. Sci 23.2 (2019): 1045-1065.

Wise management of water resources requires data. Nevertheless, the amount of streamflow data being col- lected globally continues to decline. Generating hydrologic data together with citizen scientists can help fill this grow- ing hydrological data gap. Our aim herein was to (1) per- form an initial evaluation of three simple streamflow mea- surement methods (i.e., float, salt dilution, and Bernoulli run- up), (2) evaluate the same three methods with citizen scien- tists, and (3) apply the preferred method at more sites with more people. For computing errors, we used midsection mea- surements from an acoustic Doppler velocimeter as refer- ence flows. First, we (authors) performed 20 evaluation mea- surements in headwater catchments of the Kathmandu Val- ley, Nepal. Reference flows ranged from 6.4 to 240 L s 1. Absolute errors averaged 23%, 15%, and 37% with aver- age biases of 8 %, 6 %, and 26 % for float, salt dilution, and Bernoulli methods, respectively. Second, we evaluated the same three methods at 15 sites in two watersheds within the Kathmandu Valley with 10 groups of citizen scientists (three to four members each) and one “expert” group (au- thors). At each site, each group performed three simple meth- ods; experts also performed SonTek FlowTracker midsec- tion reference measurements (ranging from 4.2 to 896 L s 1). For float, salt dilution, and Bernoulli methods, absolute er- rors averaged 41%, 21%, and 43% for experts and 63%, 28%, and 131% for citizen scientists, while biases aver- aged 41%, 19%, and 40% for experts and 52%, 7%, and 127 % for citizen scientists, respectively. Based on these re-
sults, we selected salt dilution as the preferred method. Fi- nally, we performed larger-scale pilot testing in week-long pre- and post-monsoon Citizen Science Flow campaigns in- volving 25 and 37 citizen scientists, respectively. Observed flows (n = 131 pre-monsoon; n = 133 post-monsoon) were distributed among the 10 headwater catchments of the Kath- mandu Valley and ranged from 0.4 to 425 L s 1 and from 1.1 to 1804 L s 1 in pre- and post-monsoon, respectively. Future work should further evaluate uncertainties of citizen science salt dilution measurements, the feasibility of their application to larger regions, and the information content of additional streamflow data.

### 61) Hsu, Yen-Chia, and Illah Nourbakhsh. "When human-computer interaction meets community citizen science." Communications of the ACM 63.2 (2020): 31-34.

HUMAN-COMPUTER INTERAC TION (HCI) studies the design and use of interfaces and interactive systems. HCI has been adopted successfully in modern commercial products. Recently, its use for promoting social good and pursuing sustainability known as sustainable HCI—has begun to receive wide attention. Conventionally, scientists and decision-makers apply top-down approaches to lead re- search activities that engage lay people in facilitating sustainability, such as saving energy. We introduce an alternative framework, Community Citizen Science (CCS), to closely connect research and social issues by empowering communities to produce scientific knowledge, represent their needs, address their concerns, and advocate for impact. CCS advances the current science-oriented concept to a deeper level that aims to sustain community engagement when researchers are no longer involved after the intervention of interactive systems.

### 62) Nakayama, Shinnosuke, et al. "Social information as a means to enhance engagement in citizen science‐based telerehabilitation." Journal of the Association for Information Science and Technology 70.6 (2019): 587-595.

Advancements in computer‐mediated exercise put forward the feasibility of telerehabilitation, but it remains a challenge to retain patients' engagement in exercises. Building on our previous study demonstrating enhanced engagement in citizen science through social information about others' contributions, we propose a novel framework for effective telerehabilitation that integrates citizen science and social information into physical exercise. We hypothesized that social information about others' contributions would augment engagement in physical activity by encouraging people to invest more effort toward discovery of novel information in a citizen science context. We recruited healthy participants to monitor the environment of a polluted canal by tagging images using a haptic device toward gathering environmental information. Along with the images, we displayed the locations of the tags created by the previous participants. We found that participants increased both the amount and duration of physical activity when presented with a larger number of the previous tags. Further, they increased the diversity of tagged objects by avoiding the locations tagged by the previous participants, thereby generating richer information about the environment. Our results suggest that social information is a viable means to augment engagement in rehabilitation exercise by incentivizing the contribution to scientific activities.

### 63) Pohle, Ina, et al. "Citizen science evidence from the past century shows that Scottish rivers are warming." Science of the Total Environment 659 (2019): 53-65.

Salmonid species are highly sensitive to river water temperature. Although long-term river temperature monitoring is essential for assessing drivers of change in ecological systems, these data are rarely available from statutory monitoring.

We utilized a 105-year citizen science data set of river water temperature from the River Spey, North-East Scotland, gathered during the fishing season (April–October) between 1912 and 2016. As there were gaps in the records we applied generalised additive models to reconstruct long-term daily river temperature in the fishing season from air temperature, cumulative air temperature, day length and runoff. For that, continuous hydrometeorological data have been obtained from statutory monitoring and process-based models.

Long-term warming trends of river temperature, namely an increase of 0.2 K per decade after 1961, have been mostly related to increasing air temperature of the same magnitude. Indirect impacts of rising air temperatures include less snow accumulation and snow melt as well as earlier snow melt. The snow free period starts around 2 days earlier per decade throughout the study period and 7 days earlier per decade after 1965. Consequently, the contribution of snow melt and its cooling properties to river temperature in spring are declining.

Citizen science delivered a data set that filled a vital knowledge gap in the long-term historical assessment of river temperatures. Such information provides a robust basis for future assessments of global change and can help inform decision-makers about the potential importance of enhancing the resilience of rivers and aquatic ecology to climate change.

### 64) Lüftenegger, Marko, et al. "A citizen science approach to measuring students’ achievement goals." International Journal of Educational Research 95 (2019): 36-51.

The concept of citizen science in scientific research brings researchers and laypersons together to work on research projects. Using an achievement goal theory framework, the present study employs a citizen science approach in which researchers and students collaboratively developed items assessing students’ achievement goals (mastery-approach, normative and appearance performance-approach, normative and appearance performance-avoidance goals). The newly developed scales were tested in two large studies carried out in Austria and the United Kingdom. All scales exhibited good psychometric properties (validity, reliability). Measurement invariance across the investigated subjects (mathematics and German in Austria and mathematics and English in the United Kingdom) and the two countries was established. Moreover, we investigated relations to implicit theories, self-efficacy, reference norms, and adaptive reactions to errors.

### 65) Majumder, Mary A., and Amy L. McGuire. "Data Sharing in the Context of Health-Related Citizen Science." The Journal of Law, Medicine & Ethics 48.1_suppl (2020): 167-177.

As citizen science expands, questions arise regarding the applicability of norms and policies created in the context of conventional science. This article focuses on data sharing in the conduct of health-related citizen science, asking whether citizen scientists have obligations to share data and publish findings on par with the obligations of professional scientists. We conclude that there are good reasons for supporting citizen scientists in sharing data and publishing findings, and we applaud recent efforts to facilitate data sharing. At the same time, we believe it is problematic to treat data sharing and publication as ethical requirements for citizen scientists, especially where there is the potential for burden and harm without compensating benefit.

### 66) Parrish, Julia K., et al. "Hoping for optimality or designing for inclusion: Persistence, learning, and the social network of citizen science." Proceedings of the National Academy of Sciences 116.6 (2019): 1894-1901.

The explosive growth in citizen science combined with a recalcitrance on the part of mainstream science to fully embrace this data collection technique demands a rigorous examination of the factors influencing data quality and project efficacy. Patterns of contributor effort and task performance have been well reviewed in online projects; however, studies of hands-on citizen science are lacking. We used a single hands-on, out-of-doors project—the Coastal Observation and Seabird Survey Team (COASST)—to quantitatively explore the relationships among participant effort, task performance, and social connectedness as a function of the demographic characteristics and interests of participants, placing these results in the context of a meta-analysis of 54 citizen science projects. Although online projects were typified by high (>90%) rates of one-off participation and low retention (<10%) past 1 y, regular COASST participants were highly likely to continue past their first survey (86%), with 54% active 1 y later. Project-wide, task performance was high (88% correct species identifications over the 31,450 carcasses and 163 species found). However, there were distinct demographic differences. Age, birding expertise, and previous citizen science experience had the greatest impact on participant persistence and performance, albeit occasionally in opposite directions. Gender and sociality were relatively inconsequential, although highly gregarious social types, i.e., “nexus people,” were extremely influential at recruiting others. Our findings suggest that hands-on citizen science can produce high-quality data especially if participants persist, and that understanding the demographic data of participation could be used to maximize data quality and breadth of participation across the larger societal landscape.

### 67) Hicks, Anna, et al. "Global mapping of citizen science projects for disaster risk reduction." Citizen Science: Reducing Risk and Building Resilience to Natural Hazards (2020).

Citizen science for disaster risk reduction (DRR) holds huge promise and has demonstrated success in advancing scientific knowledge, providing early warning of hazards, and contributed to the assessment and management of impacts. While many existing studies focus on the performance of specific citizen science examples, this paper goes beyond this approach to present a systematic global mapping of citizen science used for DRR in order to draw out broader insights across diverse methods, initiatives, hazards and country contexts. The systematic mapping analyzed a total of 106 cases of citizen science applied to DRR across all continents. Unlike many existing reviews of citizen science initiatives, relevance to the disaster risk context led us to ‘open up’ our mapping to a broader definition of what might constitute citizen science, including participatory research and narrative-based approaches. By taking a wider view of citizen science and opening up to other disciplinary practices as valid ways of knowing risks and hazards, we also capture these alternative examples and discuss their relevance for aiding effective decision-making around risk reduction. Based on this analysis we draw out lessons for future research and practice of citizen science for DRR including the need to: build interconnections between disparate citizen science methods and practitioners; address multi-dimensionality within and across hazard cycles; and develop principles and frameworks for evaluating citizen science initiatives that not only ensure scientific competence but also attend to questions of equity, responsibility and the empowerment of those most vulnerable to disaster risk.

### 68) Peter, Maria, Tim Diekötter, and Kerstin Kremer. "Participant outcomes of biodiversity citizen science projects: a systematic literature review." Sustainability 11.10 (2019): 2780.

*We discussed doing this at first supervisor meeting, turns out already been done!*

Citizen science is becoming increasingly popular as a format in environmental and sustainability education. Citizen science not only allows researchers to gather large amounts of biodiversity-related data, it also has the potential to engage the public in biodiversity research. Numerous citizen science projects have emerged that assume that participation in the project affects participants’ knowledge, attitudes, and behavior. We investigated what evidence really exists about the outcomes of biodiversity citizen science projects on the side of the individual participants. For this purpose, we conducted a systematic review of peer-reviewed research articles published up to and including 2017. We found evidence for various individual participant outcomes. The outcome reported most often was a gain in knowledge. Other outcomes, found in several articles, referred to changes in behavior or attitudes. Outcomes reported less often were new skills, increased self-efficacy and interest, and a variety of other personal outcomes. We discuss the research design and methods used in the reviewed studies und formulate specific recommendations for future research. We conclude that citizen science is a promising option for environmental and sustainability education focusing on biodiversity. Partnerships between natural and social scientists in the design and evaluation of projects would allow future biodiversity citizen science projects to utilize their full educational potential.

### 69) Sterrett, Sean C., et al. "The contribution of road‐based citizen science to the conservation of pond‐breeding amphibians." Journal of Applied Ecology 56.4 (2019): 988-995.


1. Roadside amphibian citizen science (CS) programmes bring together volunteers focused on collecting scientific data while working to mitigate population declines by reducing road mortality of pond‐breeding amphibians. Despite the international popularity of these movement‐based, roadside conservation efforts (i.e. “big nights,” “bucket brigades” and “toad patrols”), direct benefits to conservation have rarely been quantified or evaluated.

2. As a case study, we used a population simulation approach to evaluate how volunteer intensity, frequency and distribution influence three conservation outcomes (minimum population size, population growth rate and years to extinction) of the spotted salamander (Ambystoma maculatum ), often a focal pond‐breeding amphibian of CS and conservation programmes in the United States.

3. Sensitivity analysis supported the expectation that spotted salamander populations were primarily recruitment‐driven. Thus, conservation outcomes were highest when volunteers focused on metamorph outmigration as opposed to adult in‐migration—contrary to the typical timing of such volunteer events.

4. Almost every volunteer strategy resulted in increased conservation outcomes compared to a no‐volunteer strategy. Specifically, volunteer frequency during metamorph migration increased outcomes more than the same increases in volunteer effort during adult migration. Small population sizes resulted in a negligible effect of volunteer intensity. Volunteers during the first adult in‐migration had a relatively small effect compared to most other strategies.

5. Synthesis and applications . Although citizen science (CS)‐focused conservation actions could directly benefit declining populations, additional conservation measures are needed to halt or reverse local amphibian declines. This study demonstrates a need to evaluate the effectiveness of focusing CS mitigation efforts on the metamorph stage, as opposed to the adult stage. This may be challenging, compared to other management actions such as road‐crossing infrastructure. Current amphibian CS programmes will be challenged to balance implementing evidence‐based conservation measures on the most limiting life stage, while retaining social and community benefits for volunteers.

### 70) Van Etten, Jacob, et al. "First experiences with a novel farmer citizen science approach: Crowdsourcing participatory variety selection through on-farm triadic comparisons of technologies (tricot)." Experimental Agriculture 55.S1 (2019): 275-296.

Rapid climatic and socio-economic changes challenge current agricultural R&D capacity. The necessary quantum leap in knowledge generation should build on the innovation capacity of farmers themselves. A novel citizen science methodology, triadic comparisons of technologies or tricot, was implemented in pilot studies in India, East Africa, and Central America. The methodology involves distributing a pool of agricultural technologies in different combinations of three to individual farmers who observe these technologies under farm conditions and compare their performance. Since the combinations of three technologies overlap, statistical methods can piece together the overall performance ranking of the complete pool of technologies. The tricot approach affords wide scaling, as the distribution of trial packages and instruction sessions is relatively easy to execute, farmers do not need to be organized in collaborative groups, and feedback is easy to collect, even by phone. The tricot approach provides interpretable, meaningful results and was widely accepted by farmers. The methodology underwent improvement in data input formats. A number of methodological issues remain: integrating environmental analysis, capturing gender-specific differences, stimulating farmers' motivation, and supporting implementation with an integrated digital platform. Future studies should apply the tricot approach to a wider range of technologies, quantify its potential contribution to climate adaptation, and embed the approach in appropriate institutions and business models, empowering participants and democratizing science.

### 71) Johnson, Brian Alan, et al. "Citizen science and invasive alien species: An analysis of citizen science initiatives using information and communications technology (ICT) to collect invasive alien species observations." Global Ecology and Conservation 21 (2020): e00812.

Owing to the huge number of species observations that can be collected by non-professional scientists, “citizen science” has great potential to contribute to scientific knowledge on invasive alien species (IAS). Citizen science has existed for centuries, but the recent adoption of information and communications technology (ICT) in this field (e.g. web- or mobile application-based interfaces for citizen training and data generation) has led to a massive surge in popularity, mainly due to reduced geographic barriers to citizen participation. Several challenges exist, however, to effectively utilize citizen-generated data for monitoring IAS (or other species of interest) at the global scale. Here, we conducted a systematic analysis of citizen science initiatives collecting IAS data using ICT, hoping to better understand their scientific contributions and challenges, their similarities/differences, and their interconnections. Through a search of the Scopus database, we identified 26 initiatives whose data had been used in scientific publications related to IAS, and based our analyses on these initiatives. The most common scientific uses of these citizen science data were to visualize the spatial distribution of IAS, better understand their behaviour/phenology, and elucidate citizen science data quality issues. To alleviate data quality concerns, most initiatives (19/26) had mechanisms for verifying citizen observations, such as user-submitted photographs. While many initiatives collected similar data parameters for each species observation, only 54% of the initiatives had a practice of data sharing. This lack of data sharing causes fragmentation of the citizen-generated IAS data, and is likely inhibiting the wider usage of the data for scientific studies on IAS involving large geographic scales (e.g. regional or global) and/or broad taxonomic scopes. To reduce this fragmentation and better consolidate the collected citizen science data, finally we provide some general data sharing guidelines for citizen science initiatives as well as individual volunteers.

### 72) Matear, Liam, et al. "Cetacean biodiversity in the Bay of Biscay: suggestions for environmental protection derived from citizen science data." Marine Policy 109 (2019): 103672.

Cetacean communities face significant threats from adverse interactions with human activities such as bycatch, vessel collision, and environmental pollution. Monitoring of marine mammal populations can help to assess and safeguard marine biodiversity for future generations. Traditional surveys can be costly and time-consuming to undertake, but we explore the ability of citizen science to inform environmental assessments and subsequent conservation management. We use data collected from platforms of opportunity within the Bay of Biscay to investigate spatial changes in cetacean diversity, with the aim of identifying hotspots which may be suitable for further investigation and conservation. Seventeen species of cetaceans were recorded over a ten year period, many of which are data deficient in European waters (e.g. Bottlenose dolphin, Short-beaked common dolphin, Striped dolphin, Risso's dolphin, Long-finned pilot whale, Killer whale, Northern bottlenose whale, Cuvier's beaked whale, Sowerby's beaked whale and True's beaked whale). Biodiversity (determined by Simpson's Diversity index) ranged from 0.19 to 0.77. The central and southern areas of the survey area indicated the highest biodiversity (0.65–0.77), and these locations may benefit most from protection as Important Marine Mammal Areas. We present a case for this designation, and discuss the benefits and limitations of citizen science for informing conservation action.

### 73) Kuchinskaya, Olga. "Citizen science and the politics of environmental data." Science, Technology, & Human Values 44.5 (2019): 871-880.

In this commentary, I reflect on the differences between two independent citizen approaches to monitoring radiological contamination, one in Belarus after the 1986 Chernobyl nuclear accident and the other in Japan following the 2011 Fukushima Daiichi accident. I examine these approaches from the perspective of their contribution to making radiological contamination more publicly visible (i.e., publicly recognized as a hazard). The analysis is grounded in my earlier work (Kuchinskaya 2014), where I examined how we have come to know what we know about post–Chernobyl contamination and its effects in Belarus, a former Soviet republic most heavily affected by the fallout. As I described in this study, much of what we know about the consequences of Chernobyl is based on the work of the Belarusian nonprofit Institute of Radiation Safety, “Belrad.” I compare Belrad’s approach to radiological monitoring with the work of the volunteer network Safecast, arguably one of the best-known citizen science projects in the world, which is working to monitor the scope of the post–Fukushima contamination. Through this comparison of approaches, I raise broader questions about a form of sensing practices—data-related practices of citizen science that make environmental hazards publicly in/visible.

### 74) Callaghan, Corey T., et al. "Using citizen science data to define and track restoration targets in urban areas." Journal of Applied Ecology 56.8 (2019): 1998-2006.

1. Habitat fragmentation and land degradation, directly and indirectly caused by urbanization, are drastically altering the world's ecosystems and are therefore driving an imperative for ecological restoration within the world's cities. Current methods for the implementation and monitoring of restoration are limited. Restoration ecology needs cost‐effective and repeatable tools for tracking changes at global scales, but with local relevance.
2. We propose the Urban Greenspace Integrity Index—a locally relevant measure of an urban greenspace's response to urbanization, derived from widely accessible citizen science data. Unlike classical measurements of biodiversity (e.g. species richness, species diversity), this index measures species‐specific responses to continuous measures of urbanization.
3. Increases in this index are evidence of a successful urban restoration project; that is, restoration results in a community shift that favours urban‐sensitive species. Importantly, data for this index are easily and efficiently collected by citizen scientists, providing long‐term repeatable data. This urban index, calculated from greenspace surveys, correlates with and complements traditional biodiversity metrics.
4. Synthesis and applications . Policymakers and practitioners can use the index—a measure of the urbanness of the local bird community—to define and track restoration of urban ecosystems, effectively measuring changes in biodiversity in response to urbanization: measuring whether the urbanness of the bird community changes through time. Importantly, this index can be calculated using citizen science data, providing a potentially long‐term monitoring effort of restoration projects.

### 75) Can, Recep, Sultan Kocaman, and Candan Gokceoglu. "A convolutional neural network architecture for auto-detection of landslide photographs to assess citizen science and volunteered geographic information data quality." ISPRS International Journal of Geo-Information 8.7 (2019): 300.

Several scientific processes benefit from Citizen Science (CitSci) and VGI (Volunteered Geographical Information) with the help of mobile and geospatial technologies. Studies on landslides can also take advantage of these approaches to a great extent. However, the quality of the collected data by both approaches is often questionable, and automated procedures to check the quality are needed for this purpose. In the present study, a convolutional neural network (CNN) architecture is proposed to validate landslide photos collected by citizens or nonexperts and integrated into a mobile- and web-based GIS environment designed specifically for a landslide CitSci project. The VGG16 has been used as the base model since it allows finetuning, and high performance could be achieved by selecting the best hyper-parameters. Although the training dataset was small, the proposed CNN architecture was found to be effective as it could identify the landslide photos with 94% precision. The accuracy of the results is sufficient for purpose and could even be improved further using a larger amount of training data, which is expected to be obtained with the help of volunteers.

### 76) Hiller, Thomas, and Danny Haelewaters. "A case of silent invasion: Citizen science confirms the presence of Harmonia axyridis (Coleoptera, Coccinellidae) in Central America." PloS one 14.7 (2019): e0220082.

Harmonia axyridis (Coleoptera, Coccinellidae) is a globally invasive ladybird. It has been intentionally introduced in many countries as a biological control agent, whereas it has been unintentionally released in many others. Climatic factors are important in limiting the spread of H. axyridis. For example, very few records are known from tropical or desert regions. Currently, no published reports are known from Central America. Here, we report H. axyridis from Costa Rica, Guatemala, Honduras, Panama, and Puerto Rico. Specimens were either observed by the authors, discovered in dried insect collections, or retrieved from searching through online photographs available from the citizen science project iNaturalist and the photo-sharing website Flickr. These new records and the wide distribution of H. axyridis in Latin America suggest several invasion events, which have gone unnoticed until now. We stress the need for further, large-scale monitoring and show the advantage of citizen science to assess the presence of invasive alien species.

### 77) Weiser, Emily L., et al. "Challenges for leveraging citizen science to support statistically robust monitoring programs." Biological Conservation 242 (2020): 108411.

Large samples and long time series are often needed for effective broad-scale monitoring of status and trends in wild populations. Obtaining those sample sizes can be more feasible when volunteers contribute to the dataset, but volunteer-selected sites are not always representative of a population. Previous work to account for biased site selection has relied on knowledge of covariates to explain differences between site types, but such knowledge is often unavailable. For cases where relevant covariates have not been defined, we used a simulation study to identify the consequences of including non-probabilistically selected sites (NP sites) in addition to sites selected from a probability-based design (P sites), test modeling frameworks that might correct for biases, and evaluate whether those frameworks could allow NP sites to reduce the sampling requirement for P sites and potentially reduce costs of monitoring. We informed the simulation with pilot data from surveys of monarch butterflies and their obligate larval host plant, milkweed. We found strong biases in NP sites versus P sites in density and trends of monarchs and milkweed. Modeling frameworks that accounted for site type with a group effect or that strongly downweighted NP sites successfully produced unbiased estimates. However, sampling more NP sites typically did not improve accuracy or precision, and adding NP sites sometimes required also adding P sites to prevent biases. Further work on novel modeling frameworks would be useful to allow citizen-science data to contribute useful information to conservation.

### 78) Skarlatidou, Artemis, et al. "What do volunteers want from citizen science technologies? A systematic literature review and best practice guidelines." JCOM: Journal of Science Communication 18.1 (2019).

*Systematic review*

Although hundreds of citizen science applications exist, there is lack of detailed analysis of volunteers' needs and requirements, common usability mistakes and the kinds of user experiences that citizen science applications generate. Due to the limited number of studies that reflect on these issues, it is not always possible to develop interactions that are beneficial and enjoyable. In this paper we perform a systematic literature review to identify relevant articles which discuss user issues in environmental digital citizen science and we develop a set of design guidelines, which we evaluate using cooperative evaluation. The proposed research can assist scientists and practitioners with the design and development of easy to use citizen science applications and sets the basis to inform future Human-Computer Interaction research in the context of citizen science.

### 79) Fiske, Amelia, Barbara Prainsack, and Alena Buyx. "Meeting the needs of underserved populations: setting the agenda for more inclusive citizen science of medicine." Journal of medical ethics 45.9 (2019): 617-622.

In its expansion to genomic, epidemiological and biomedical research, citizen science has been promoted as contributing to the democratisation of medical research and healthcare. At the same time, it has been criticised for reinforcing patterns of exclusion in health and biomedicine, and sometimes even creating new ones. Although citizen science has the potential to make biomedical research more inclusive, the benefits of current citizen science initiatives are not equally accessible for all people—in particular those who are resource-poor, located outside of traditional networks of healthcare services, or members of minorities and marginalised groups. In view of growing public investments in participatory research endeavours, we argue that it should be considered more explicitly if, and how, citizen science could help make research more inclusive, contribute to the public good, and possibly even lead to better and more equitable healthcare. Reflecting on emerging ethical concerns for scientific conduct and best medical practice, we propose a set of relevant considerations for researchers, practitioners, bioethicists, funders and participants who seek to advance ethical practices of citizen-led health initiatives, and address profound differences in position, privilege and power in research.

### 80) Dawson, Tom, et al. "Coastal heritage, global climate change, public engagement, and citizen science." Proceedings of the National Academy of Sciences 117.15 (2020): 8280-8286.

Climate change is threatening an uncalculated number of archaeological sites globally, totaling perhaps hundreds of thousands of culturally and paleoenvironmentally significant resources. As with all archaeological sites, they provide evidence of humanity’s past and help us understand our place in the present world. Coastal sites, clustered at the water’s edge, are already experiencing some of the most dramatic damage due to anthropogenic climate change, and the situation is predicted to worsen in the future. In the face of catastrophic loss, organizations around the world are developing new ways of working with this threatened coastal resource. This paper uses three examples from Scotland, Florida, and Maine to highlight how new partnerships and citizen science approaches are building communities of practice to better manage threatened coastal heritage. It compares methods on either side of the Atlantic and highlights challenges and solutions. The approaches are applicable to the increasing number of heritage sites everywhere at risk from climate change; the study of coastal sites thus helps society prepare for climate change impacts to heritage worldwide.

### 81) Peters, Michael A., and Tina Besley. "Citizen science and post-normal science in a post-truth era: Democratising knowledge; socialising responsibility." (2019): 1293-1303.

*no abstract?*

The question of how scientific theories, concepts and methods change over time is an enduring issue. Science, like all forms of intellectual activity, can undergo rapid and dramatic periods of change, as it did during the Newtonian period sometimes called the ‘Scientific Revolution’ of the 17th century. In other times, change has been very gradual. Questions of this nature occupied Thomas Kuhn who in The Structure of Scientific Revolutions (1970) argued for a philosophical conception of scientific change based on historical evidence... 

### 82) He, Yurong, et al. "Evolving interest and sense of self in an environmental citizen science program." Ecology and Society 24.2 (2019).

Citizen science is a growing phenomenon across many branches of environmental science facilitating both increased science literacy and the collection of highly rigorous, longitudinal data. Understanding the motivations of adults to join and remain active in citizen science programs is important as the diversity and abundance of opportunities for public participation in science grow. We conducted a mixed-methods study of newly recruited and “seasoned” (1 year plus) participants in the Coastal Observation and Seabird Survey Team, a hands-on, environmental citizen science program focused on adult coastal residents, to explore the degree to which engagement, measured as time in the program, influenced motivation. We used constructs of functionalism, person-object theory of interest, and activity theoretic approaches to situational identity to deconstruct motivation into three interacting components: objects of interest, actions directed toward those objects, and situated senses of self. Newly recruited participants came with a strong interest in being outside on the beach and learning about birds and saw themselves as data collectors defined in part by their birding and degree/job-based credentials and their social relationships. By contrast, seasoned participants aligned their interests and situational identity more directly with the program, calling out the importance of program data and results, elevating science-based actions such as monitoring over learning, intensifying their desire to contribute to science, subjugating individual attributes in favor of their science identity, and increasing their sense of self-worth attached to the project. Our results suggest that hands-on, environmental citizen science programs focused on adults should shape their data collector roles and projects around context-specific motivations including senses of place and biodiversity, support both the altruistic and self-interest needs of participants, and combine rigorous science experience with social interaction.

### 83) Cheung, Wing, and David Feldman. "Can Citizen Science Promote Flood Risk Communication?." Water 11.10 (2019): 1961.

This article explores the challenges facing citizen science as a means of joining the efforts of scientists and flood-risk affected stakeholders in motivating citizen involvement in identifying and mitigating flood risks. While citizen science harbors many advantages, including a penchant for collaborative research and the ability to motivate those affected by floods to work with scientists in elucidating and averting risk, it is not without challenges in its implementation. These include ensuring that scientists are willing to share authority with amateur citizen scientists, providing forums that encourage debate, and encouraging equal voice in developing flood risk mitigation strategies. We assess these challenges by noting the limited application of citizen science to flood-relevant problems in existing research and recommend future research in this area to meaningfully incorporate a “re-imagined” citizen science process that is based on the participatory theoretical framework. We also discuss one case study where the principles of collaboration, debate, and equal voice were put into play in an effort to apply citizen science and—in the long term—mitigate flood hazards in one set of communities.

### 84) Gibson, Kesley J., et al. "Utility of citizen science data: A case study in land-based shark fishing." Plos one 14.12 (2019): e0226782.

Involving citizen scientists in research has become increasingly popular in natural resource management and allows for an increased research effort at low cost, distribution of scientific information to relevant audiences, and meaningful public engagement. Scientists engaging fishing tournament participants as citizen scientists represent ideal scenarios for testing citizen science initiatives. For example, the Texas Shark Rodeo has begun shifting to conservation-oriented catch-and-release practices, which provides a unique opportunity to collect data on a large scale for extended periods of time, particularly through tagging large numbers of sharks for very little cost compared to a directed scientific study. However, critics are somewhat skeptical of citizen science due to the potential for lack of rigor in data collection and validation. A major management concern for shark fisheries is the ability of anglers to identify species. We tested some of the assumptions and value of citizen-collected data by cross-verifying species identification. Specifically, the purpose of this study was to evaluate the accuracy of shark species identifications made by anglers fishing in the Texas Shark Rodeo using photographs that were submitted as a requirement for tournament participation. Using a confusion matrix, we determined that anglers correctly identified 97.2% of all shark catches submitted during the Texas Shark Rodeo from 2014–2018; however, smaller sharks and certain species, including blacknose and spinner sharks, were more difficult to identify than others. Most commonly confused with blacktip sharks, spinner sharks were most commonly identified incorrectly (76.1% true positive rate [TPR]) followed by blacknose (86.8% TPR), finetooth (88.0% TPR), and Atlantic sharpnose sharks (93.8% TPR). This study demonstrated that citizen scientists have the ability to identify sharks with relatively low error. This is important for science and management, as these long-term datasets with relatively wide geographic scope could potentially be incorporated into future assessments of sharks in the Gulf of Mexico.

### 85) Rasmussen, Lisa M. "Confronting research misconduct in citizen science." Citizen Science: Theory and Practice 4.1 (2019).

So, you suspect that someone in a citizen science project committed research misconduct. What do you do now? As citizen science methods become increasingly popular, it seems inevitable that at some point, someone identifying themselves as a citizen scientist will be accused of committing research misconduct. Yet the growth of the field also takes research increasingly outside of traditional regulatory mechanisms of identifying, investigating, and delivering consequences for research misconduct. How could we prevent or handle an allegation of scientific misconduct in citizen science that falls outside of our familiar regulatory remedies? And more broadly, what does this imply for ensuring scientific integrity in citizen science?
I argue that the increasing use of new research methods in citizen science poses a challenge to traditional approaches to research misconduct, and that we should consider how to confront issues of research misconduct in citizen science. I briefly describe existing approaches to research misconduct and some aspects of citizen science giving rise to the problem, then consider alternative mechanisms, ranging from tort law to professional responsibility to a proposed “research integrity insurance,” that might be deployed to address and prevent such cases.

### 86) Porter, W. Tanner, et al. "Citizen science informs human-tick exposure in the Northeastern United States." International journal of health geographics 18.1 (2019): 9.

Background: Tick-borne disease is the result of spillover of pathogens into the human population. Traditionally, literature has focused on characterization of tick-borne disease pathogens and ticks in their sylvatic cycles. A lim- ited amount of research has focused on human-tick exposure in this system, especially in the Northeastern United States. Human-tick interactions are crucial to consider when assessing the risk of tick-borne disease since a tick bite is required for spillover to occur.

Methods: Citizen scientists collected ticks from the Northeastern US through a free nationwide program. Submit- ted ticks were identified to species, stage, and sex. Blacklegged ticks, Ixodes scapularis, were tested for the presence of Borrelia burgdorferi sensu lato (s.l.) and hard-tick relapsing fever Borrelia. Seasonality of exposure and the citizen sci- ence activity during tick exposure was recorded by the citizen scientist. A negative binomial model was fit to predict county level CDC Lyme disease cases in 2016 using citizen science Ixodes scapularis submissions, state, and county population as predictor variables.

Results: A total of 3740 submissions, comprising 4261 ticks, were submitted from the Northeastern US and were reported to be parasitizing humans. Of the three species submitted, blacklegged ticks were the most prevalent followed by American dog ticks and lone star ticks. Submissions peaked in May with the majority of exposure occur- ring during every-day activities. The most common pathogen in blacklegged ticks was B. burgdorferi s.l. followed by hard-tick relapsing fever Borrelia. Negative binomial model performance was best in New England states followed by Middle Atlantic states.

Conclusions: Citizen science provides a low-cost and effective methodology for describing the seasonality and characteristics of human-tick exposure. In the Northeastern US, everyday activities were identified as a major mecha- nism for tick exposure, supporting the role of peri-domestic exposure in tick-borne disease. Citizen science provides a method for broad pathogen and tick surveillance, which is highly related to human disease, allowing for inferences to be made about the epidemiology of tick-borne disease.

### 87) Tran, Viet-Thi, et al. "Patients’ perspective on how to improve the care of people with chronic conditions in France: a citizen science study within the ComPaRe e-cohort." BMJ quality & safety 28.11 (2019): 875-886.

Background: This study aimed to involve patients with chronic conditions in generating ideas for improving their care.

Methods: We performed a citizen science study. Participants were adult patients with chronic conditions recruited in Community of Patients for Research ‘ComPaRe,’ a French e-cohort of patients with chronic conditions. Participants generated ideas to improve their care in answer to the open-ended question, ‘If you had a magic wand, what would you change in your healthcare?’ Three researchers and two patients independently extracted ideas from open-ended answers by using thematic analysis. Ideas were grouped into areas for improvement at the consultation, hospital/clinic and health system levels. Findings were validated and enriched by a second sample of participants recruited in ComPaRe.

Results: Between May 2017 and April 2018, a total of 1636 patients provided 3613 ideas to improve consultations (1701 ideas related to 58 areas for improvement), hospitals/clinics (928 ideas related to 41 areas for improvement) and the health system (984 ideas related to 48 areas for improvement). At the consultation level, most ideas were related to improving physician–patient discussions, informing patients about their own care, and adapting treatment to patient preferences and context. At the hospital/clinic level, most ideas aimed at improving the coordination and collaboration in care. At the health system level, most ideas were related to decreasing the administrative burden imposed on patients, improving access to care and reducing the costs of care.

Conclusion: Patients have many ideas to improve their care, from the content of consultations to the organisation of hospitals. Our study provides the proof of concept for a method to leverage patients’ practical knowledge of the care system to improve it.

### 88) Lernout, Tinne, et al. "Prevalence of pathogens in ticks collected from humans through citizen science in Belgium." Parasites & vectors 12.1 (2019): 550.

Background: In order to evaluate the risk of human exposure to tick-borne pathogens in Belgium, a study on the prevalence of several pathogens was conducted on feeding ticks removed from humans in 2017.

Methods: Using a citizen science approach based on an existing notification tool for tick bites, a sample of ticks was collected across the country. Collected ticks were screened by PCR for the presence of the following pathogens: Anaplasma phagocytophilum, Babesia spp., Borrelia burgdorferi (sensu lato), Borrelia miyamotoi, Neoehrlichia mikurensis, Rickettsia helvetica and tick-borne encephalitis virus (TBEV).

Results: In total, 1599 ticks were included in the sample. The great majority of ticks belonged to Ixodes ricinus (99%); other tick species were identified as Ixodes hexagonus (0.7%) and Dermacentor reticulatus (0.3%). Borrelia burgdorferi (s.l.) was detected in 14% of nymphs and adult ticks. Adult ticks (20%) were more likely to be infected than nymphs (12%). The most common genospecies were B. afzelii (52%) and B. garinii (21%). Except for TBEV, the other tick-borne pathogens studied were all detected in the tick sample, although at a lower prevalence: 1.5% for Babesia spp.; 1.8% for A. phagocytophilum; 2.4% for B. miyamotoi; 2.8% for N. mikurensis; and 6.8% for R. helvetica. Rickettsia raoultii, the causative agent of tick-borne lymphadenopathy, was identified for the first time in Belgium, in two out of five D. reticulatus ticks. Co-infections were found in 3.9% of the examined ticks. The most common co-infection was B. burgdorferi (s.l.)+ N. mikurensis.

Conclusions: Although for most of the tick-borne diseases in Belgium, other than Lyme borreliosis, no or few cases of human infection are reported, the pathogens causing these diseases were all (except for TBEV) detected in the tick study sample. Their confirmed presence can help raise awareness among citizens and health professionals in Belgium on possible diseases other than Lyme borreliosis in patients presenting fever or other non-characteristic symptoms after a tick bite.

### 89) Carbery, Maddison, et al. "Baseline analysis of metal (loid) s on microplastics collected from the Australian shoreline using citizen science." Marine Pollution Bulletin 152 (2020): 110914.

Microplastics are an emerging contaminant in aquatic environments. Information on the occurrence and characteristics of microplastics in Australia is limited and their interactions with chemical contaminants have not been addressed. Therefore, the aim of this study was to generate baseline information on the physical and chemical characteristics of microplastics on Australian shorelines to facilitate further detailed risk assessment. Field collected microplastics were categorised by colour, shape and polymer type. Plastic particles were primarily clear, blue, white and green and consisted mainly of fragments (57.80%) and pellets (30.68%). Polymer characterisation revealed that shoreline microplastics were polyethylene (53.17%), polypropylene (35.17%), polystyrene (6.61%) and polyethylene terephthalate (1.85%). Analysis of metal(loid)s found that concentrations of Mn, Cr, Cu, As, Zn and Pb were significantly higher on microplastics associated with industrial locations compared with other land uses, indicating that aged microplastics have the potential to adsorb toxic metals and that metals levels may be location-dependent.

### 90) Steven, Rochelle, et al. "Aligning citizen science with best practice: Threatened species conservation in Australia." Conservation Science and Practice 1.10 (2019): e100.

Well‐designed citizen science projects can improve the capacity of the scientific community to detect and understand declines in threatened species, and with the emergence of frameworks to guide good design, there is an opportunity to test whether projects are aligned with best practice. We assessed the current landscape of citizen science projects for threatened species conservation via a content analysis of the online communique of citizen science projects across Australia. Only 2% of projects stated clear research questions, although approximately 86% had implied project objectives aimed at threatened species conservation. Most projects were focused on field‐based monitoring activities with half using structured ecological survey methods. Most reviewed projects (65%) shared data with open access biodiversity databases and the vast majority use at least one social media platform to communicate with potential and existing participants (up to 81%). Approximately 50% present citizen‐sourced data summaries or publications on their websites. Our study shows there is a very strong foundation for public participation in threatened species conservation activities in Australia, yet there is scope to further integrate the principles of citizen science best practice. Improved integration of these principles will likely yield better outcomes for threatened species as well as for the citizen scientists themselves.

### 91) See, Linda. "A review of citizen science and crowdsourcing in applications of pluvial flooding." Frontiers in Earth Science 7 (2019): 44.

Pluvial flooding can have devastating effects, both in terms of loss of life and damage. Predicting pluvial floods is difficult and many cities do not have a hydrodynamic model or an early warning system in place. Citizen science and crowdsourcing have the potential for contributing to early warning systems (EWS) and can also provide data for validating flood forecasting models. Although there are increasing applications of citizen science and crowdsourcing in fluvial hydrology, less is known about activities related to pluvial flooding. Hence the aim of this paper is to review current activities in citizen science and crowdsourcing with respect to applications of pluvial flooding. Based on a search in Scopus, the papers were first filtered for relevant content and then classified into four main themes. The first two themes were divided into (i) applications relevant during a flood event, which includes automated street flooding detection using crowdsourced photographs and sensors, analysis of social media, and online and mobile applications for flood reporting; and (ii) applications related to post-flood events. The use of citizen science and crowdsourcing for model development and validation is the third theme while the development of integrated systems is theme four. All four main areas of research have the potential to contribute to EWS and build community resilience. Moreover, developments in one will benefit others, e.g., further developments in flood reporting applications and automated flood detection systems will yield data useful for model validation.

### 92) Golumbic, Yaela N., Barak Fishbain, and Ayelet Baram-Tsabari. "User centered design of a citizen science air-quality monitoring project." International Journal of Science Education, Part B 9.3 (2019): 195-213.

Technological developments, social networking and the emergence of sensory micro-computation platforms have facilitated the recent growth of citizen science-public participation in scientific research. Citizen science provides lay audiences platforms for data collection and classification alongside access to large scientific databases. Although these platforms are intended for non-experts, they are often designed by scientists, who may not fully appreciate their importance. This may result in platforms that are incompatible with users’ needs and thus underused . This article describes the use of Human Computer Interactions (HCI) in a citizen science project for monitoring air-quality in the local environment. Using interviews, focus groups, questionnaires and log data from the project website (n=138), in a three-phase iterative process, we identified public requirments from an online data presentation platform. The findings suggest participants were interested in real time, local, easy to understand information, which is practical, ready-to-use and presented in the context. These insights were implemented in the design of a new platform, constructed as a simple three-layer information display with representations of air-quality standards and practical recommendations. We examine participants’ use of the platform and discuss motivations and impediments to participation in the future design of citizen science projects for enhancing public engagement in science.

### 93) Couch, Jennifer, Katrina Theisz, and Elizabeth Gillanders. "Engaging the public: citizen science." Strategies for Team Science Success. Springer, Cham, 2019. 159-167.

In this chapter, you will learn more about citizen science and related methods which aim to involve the public in scientific research. We define citizen science as a collaborative approach to research involving the public, not just as subjects of the research or advisors to the research but as direct collaborators and partners in all aspects the research process itself. Citizen science is a complex set of methods that includes an ever-expanding lexicon of related terms which are constantly evolving (e.g., participatory action research, public participation in scientific research, etc.). A particular emphasis will be given to community-based participatory research (CBPR) and community-engaged research (CEnR) in Chap.  9. Here, we will focus primarily on the usefulness of citizen science methods in scientific research and how it has become the ultimate team science.

### 94) Chen, Hongzhe, et al. "A nationwide assessment of litter on China’s beaches using citizen science data." Environmental Pollution 258 (2020): 113756.

China is the largest plastic consumer in the world. Despite its plastic waste import ban in 2017, this populous economy inevitably generates a large amount of waste, including plastic waste, a considerable part of which has become marine litter. Data from the 2018 National Coastal Cleanup and Monitoring Project, the largest beach litter monitoring activities using the citizen science approach in China, have been retrieved and analyzed to understand spatial patterns, composition, and original usage of marine litter. Within this project, 24 beaches were surveyed every two months. As a result, the mean density was 3.85 ± 5.39 items m - 2, much higher than that reported by previous studies in China. There were great differences in the spatial distribution of litter. The highest densities appeared in the runoff-affected area of the Yangtze River, which was another difference from previous studies. Low-density, easy-to-transport foamed plastics were the major contributor to marine litter in these areas. Along China’s coast, approximately 90% of litter was from land-based sources, and over half of that originated from domestic sources. Including foamed plastic products, plastic litter with low recycling value dominated. Both natural and human factors influencing the spatiotemporal distribution and composition of litter are discussed. Socioeconomic factors, such as the lifestyle and consumption levels of citizens and local waste management systems, are possible explanations for the low-value characteristic of marine litter. The deviation between previous data and citizen science data in this study may be caused by many factors. Based on the discussion on these factors, some suggestions for citizen science research in China are also put forward.

### 95) Ryan, Sean F., et al. "Global invasion history of the agricultural pest butterfly Pieris rapae revealed with genomics and citizen science." Proceedings of the National Academy of Sciences 116.40 (2019): 20015-20024.

Over the last few thousand years, the seemingly inconspicuous cabbage white butterfly, Pieris rapae, has become one of the most abundant and destructive butterflies in the world. Here, we assessed variation at thousands of genetic markers from butterflies collected across 32 countries by over 150 volunteer scientists and citizens to reconstruct the global spread of this agricultural pest. Our results suggest this butterfly spread out from eastern Europe to occupy every continent except South America and Antarctica, with the timing of many of these events coinciding with human activities—migration, trade, and the development of crop cultivars that serve as food plants for the butterfly larvae. Interestingly, many of these invasions were hugely successful despite repeated losses of genetic diversity.

### 96) Davids, Jeffrey C., et al. "Soda bottle science—citizen science monsoon precipitation monitoring in Nepal." Frontiers in earth science 7 (2019): 46.

Citizen science, as a complement to ground-based and remotely-sensed precipitation measurements, is a promising approach for improving precipitation observations. During the 2018 monsoon (May to September), SmartPhones4Water (S4W) Nepal—a young researcher-led water monitoring network—partnered with 154 citizen scientists to generate 6,656 precipitation measurements in Nepal with low-cost (<1 USD) S4W gauges constructed from repurposed soda bottles, concrete, and rulers. Measurements were recorded with Android-based smartphones using Open Data Kit Collect and included GPS-generated coordinates, observation date and time, photographs, and observer-reported readings. A year-long S4W gauge intercomparison revealed a - 2.9% error compared to the standard 203 mm (8-inch) gauge used by the Department of Hydrology and Meteorology (DHM), Nepal. We analyzed three sources of S4W gauge errors: evaporation, concrete soaking, and condensation, which were 0.5 mm day - 1 (n = 33), 0.8 mm (n = 99), and 0.3 mm (n = 49), respectively. We recruited citizen scientists by leveraging personal relationships, outreach programs at schools/colleges, social media, and random site visits. We motivated ongoing participation with personal follow-ups via SMS, phone, and site visit; bulk SMS; educational workshops; opportunities to use data; lucky draws; certificates of involvement; and in certain cases, payment. The average citizen scientist took 42 measurements (min = 1, max = 148, stdev = 39). Paid citizen scientists (n = 37) took significantly more measurements per week (i.e., 54) than volunteers (i.e., 39; alpha level = 0.01). By comparing actual values (determined by photographs) with citizen science observations, we identified three categories of observational errors (n = 592; 9% of total measurements): unit (n = 50; 8% of errors; readings in centimeters instead of millimeters); meniscus (n = 346; 58% of errors; readings of capillary rise), and unknown (n = 196; 33% of errors). A cost per observation analysis revealed that measurements could be performed for as little as 0.07 and 0.30 USD for volunteers and paid citizen scientists, respectively. Our results confirm that citizen science precipitation monitoring with low-cost gauges can help fill precipitation data gaps in Nepal and other data scarce regions.

### 97) Rappold, A. G., et al. "Smoke Sense Initiative Leverages Citizen Science to Address the Growing Wildfire‐Related Public Health Problem." GeoHealth 3.12 (2019): 443-457.

Smoke Sense is a citizen science project with investigative, educational, and action‐oriented objectives at the intersection of wildland fire smoke and public health. Participants engage with a smartphone application to explore current and forecast visualizations of air quality, learn about how to protect health from wildfire smoke, and record their smoke experiences, health symptoms, and behaviors taken to reduce their exposures to smoke. Through participation in the project, individuals engage in observing changes in their environment and recording changes in their health, thus facilitating progression on awareness of health effects of air pollution and adoption of desired health‐promoting behaviors. Participants can also view what others are reporting. Data from the pilot season (1 August 2017 to 7 January 2018; 5,598 downloads) suggest that there is a clear demand for personally relevant data during wildfire episodes motivated by recognition of environmental hazard and the personal concern for health. However, while participants shared clear perceptions of the environmental hazard and health risks in general, they did not consistently recognize their own personal health risk. The engagement in health protective behavior was driven in response to symptoms rather than as preventive courses of action. We also observed clear differences in the adoption likelihood of various health protective behaviors attributed to barriers and perceived benefits of these actions. As users experience a greater number and severity of symptoms, the perceived benefits of taking health protective actions exceeded the costs associated with the barriers and thus increased adoption of those actions. Based on pilot season data, we summarize key insights which may improve current health risk communications in nudging individuals toward health protective behavior; there is a need to increase personal awareness of risk and compelling evidence that health protective behaviors are beneficial.

### 98) Debes, John H., et al. "A 3 Gyr White Dwarf with Warm Dust Discovered via the Backyard Worlds: Planet 9 Citizen Science Project." The Astrophysical Journal Letters 872.2 (2019): L25.

Infrared excesses due to dusty disks have been observed orbiting white dwarfs with effective temperatures between 7200 and 25,000 K, suggesting that the rate of tidal disruption of minor bodies massive enough to create a coherent disk declines sharply beyond 1 Gyr after white dwarf formation. We report the discovery that the candidate white dwarf LSPM J0207+3331, via the Backyard Worlds: Planet 9 citizen science project and Keck Observatory follow-up spectroscopy, is hydrogen dominated with a luminous compact disk (L IR/L star = 14%) and an effective temperature nearly 1000 K cooler than any known white dwarf with an infrared excess. The discovery of this object places the latest time for large-scale tidal disruption events to occur at ~3 Gyr past the formation of the host white dwarf, making new demands of dynamical models for planetesimal perturbation and disruption around post-main-sequence planetary systems. Curiously, the mid-infrared photometry of the disk cannot be fully explained by a geometrically thin, optically thick dust disk as seen for other dusty white dwarfs, but requires a second ring of dust near the white dwarf's Roche radius. In the process of confirming this discovery, we found that careful measurements of WISE source positions can reveal when infrared excesses for white dwarfs are co-moving with their hosts, helping distinguish them from confusion noise.

### 99) Kimura, Aya H. "Citizen science in post-Fukushima Japan: the gendered scientization of radiation measurement." Science as Culture 28.3 (2019): 327-350.

*I also have her book on this topic, v good, but a bit pomo*

After the Fukushima nuclear accident, many laywomen established citizen radiation measuring organizations (CRMOs) to measure the concentration of radioactive materials in food to ensure its safety. These women had diverse motivations. As caretakers, many wanted to protect their families. Others saw it as important to arm themselves with science when the broader social discourse portrayed contamination concerns as irrational and harmful to food producers, and stereotyped women as overreacting due to their scientific illiteracy. Some women also became empowered and productive citizen scientists, influenced by the popular idea of women-in-science. The fluid relationships between scientization and citizens’ collective mobilizations make it particularly illuminating to analyze such shifting relationships between activism and science using Gieryn’s concept of boundary-work. Women’s motivations to participate in CRMOs were closely connected to the expanding scientization—the increasing role of science in defining and prescribing social problems. While they shared many sentiments with anti-nuclear movements, women often performed boundary-work in a way that constructed science as irreconcilable with activism. Many saw activism as threatening the legitimation provided by science: a particularly important issue for women, who were stereotyped and policed as anti-science and irrational after the accident. Activism was also understood as a highly masculinized space incompatible with the feminized caretaker role that many women took on, which initially provided the rationale for their involvement in citizen science. The concept of gendered scientization highlights how the turn to science in dealing with environmental threats might result in gendered opportunities and challenges in collective mobilization by citizens.

### 100) Jiménez, Manuel, Isaac Triguero, and Robert John. "Handling uncertainty in citizen science data: Towards an improved amateur-based large-scale classification." Information Sciences 479 (2019): 301-320.

Citizen Science, traditionally known as the engagement of amateur participants in research, is showing great potential for large-scale processing of data. In areas such as astronomy, biology, or geo-sciences, where emerging technologies generate huge volumes of data, Citizen Science projects enable image classification at a rate not possible to accomplish by experts alone. However, this approach entails the spread of biases and uncertainty in the results, since participants involved are typically non-experts in the problem and hold variable skills. Consequently, the research community tends not to trust Citizen Science outcomes, claiming a generalised lack of accuracy and validation.

We introduce a novel multi-stage approach to handle uncertainty within data labelled by amateurs in Citizen Science projects. Firstly, our method proposes a set of transformations that leverage the uncertainty in amateur classifications. Then, a hybridisation strategy provides the best aggregation of the transformed data for improving the quality and confidence in the results. As a case study, we consider the Galaxy Zoo, a project pursuing the labelling of galaxy images. A limited set of expert classifications allow us to validate the experiments, confirming that our approach is able to greatly boost accuracy and classify more images with respect to the state-of-art.


